# Predicting Cross-Border Music Diffusion on Spotify

## Business Context

When a song enters a national Spotify chart for the first time, marketing teams and playlist curators face an immediate question: **which other countries will this song chart in next?** Answering this within days — not weeks — enables targeted ad spend, localized playlist placement, and coordinated label rollouts across 66 global markets.

This notebook builds a **Top-5 Country Ranker**: given a song's first chart appearance, it predicts the 5 countries most likely to see the song chart within 60 days. The underlying dataset contains 25.1M chart observations spanning 2017–2021 across 66 markets, which are feature-engineered into ~3.46M (track, target_country) prediction rows — 272,922 for training (downsampled to 5:1 negative-to-positive ratio to address the 110:1 class imbalance), and 1,647,221 / 1,535,867 for validation / testing at full class distribution to ensure unbiased evaluation.

**Why 60 days?** Our EDA on viral shows that cross-border chart entry follows a heavy-tailed distribution: that 75% of international spread occurs within the first 2–4 weeks after initial charting, with a long tail extending to ~60 days. Beyond 60 days, remaining entries are rare and largely driven by external events (e.g. Christmas, TikTok virality, movie soundtracks) rather than organic diffusion patterns the model can capture. The 60-day window balances recall of genuine spread events against noise from coincidental late entries.

**Why Top-5?** Tracks that spread internationally chart in a median of 5.17 additional countries (among tracks that spread at all). Predicting k=5 countries aligns with this empirical distribution — it is large enough to capture the typical spread footprint while remaining actionable for marketing teams who need to prioritize a small set of target markets. At k=3, the theoretical recall ceiling is too low (~58%); at k=10, the list becomes less actionable and precision drops substantially.

## Technical Approach

We address two prediction tasks:

1. **Country ranking** — which countries will a song chart in? We train a linear baseline (Logistic Regression) and a gradient-boosted model (XGBRanker), then compare.
2. **Timing prediction** — when will it chart there? We train a linear baseline (Linear Regression) and a gradient-boosted model (XGBRegressor), then compare.

For each task, the linear baseline establishes what simple decision boundaries can capture and provides interpretable coefficients, while the gradient-boosted model captures non-linear feature interactions.

All four models plus the naive popularity baseline are listed here:

| Model | Task | Type | Purpose |
|-------|------|------|---------|
| Naive popularity baseline | Ranking | Heuristic | Lower bound — always predict the 5 most popular countries |
| Logistic Regression | Ranking | Linear baseline | Establishes linear ceiling; interpretable coefficients |
| XGBRanker | Ranking | Primary model | Listwise ranking with `rank:ndcg`; captures non-linear interactions |
| Linear Regression | Timing | Linear baseline | Establishes linear ceiling for days-to-entry prediction |
| XGBRegressor | Timing | Primary model | Non-linear timing prediction with target transforms |

### Why XGBoost?

We chose gradient-boosted decision trees (XGBoost) over alternative model families for several reasons:

- **Tabular data strength:** Our feature matrix consists of heterogeneous tabular features (continuous distances, categorical flags, count statistics). Gradient boosting consistently outperforms neural networks on structured tabular data (Grinsztajn et al., 2022), and our dataset lacks the sequential or spatial structure that would favor RNNs or CNNs.
- **Native learning-to-rank support:** XGBoost's `XGBRanker` with `rank:ndcg` directly optimizes the listwise ranking objective we care about. Random forests and standard neural networks require custom loss functions or surrogate objectives for ranking tasks.
- **Handling of missing values:** 19.4% of country pairs lack Hofstede cultural distance data (non-Western countries not in the database). During feature engineering, missing `cultural_dist_min` values are imputed with the global median (1.620) and a binary `cultural_dist_missing` flag preserves the missingness signal. XGBoost can then learn different split behavior for imputed vs observed distances.
- **Interpretability:** Feature importance via gain decomposition allows us to validate that the model relies on meaningful cultural and geographic signals, not artifacts.
- **XGBoost vs LightGBM:** Both are competitive gradient boosting frameworks. We chose XGBoost for its mature `XGBRanker` API and broader academic adoption. LightGBM's `lambdarank` is a viable alternative but offered no clear advantage for our dataset size.

### Why Learning-to-Rank over Pointwise Classification?

Our task is inherently a ranking problem: given a track, produce an ordered list of countries. Two formulations are possible:

- **Pointwise classification** : Train a binary classifier on each (track, country) pair to predict P(entry). Rank countries by predicted probability. This ignores inter-country dependencies — the model doesn't know that predicting "Germany" affects the optimal prediction for "Austria."
- **Listwise learning-to-rank**: XGBRanker with `rank:ndcg` optimizes the *ordering* directly, using group-aware gradients that consider all candidates for each track simultaneously.

For our Business Case the XGBRanker definetly fulfills our target in a better way, thats why we will focus on this.

## Table of Contents

This notebook follows an **approach → metrics → results → selection** structure.

**Setup & Data**
- [1. Setup and Helper Functions](#1.-Setup-and-Helper-Functions) — Temporal split, metrics, scoring utilities
- [2. Feature Selection](#2.-Feature-Selection) — Pruning zero-gain features from prior notebooks

**Methodology**
- [3. Evaluation Metrics — Why These Metrics?](#3.-Evaluation-Metrics-—-Why-These-Metrics?) — Ranking metrics, timing metrics, baselines, metric justification
- [4. Model Approaches — Overview](#4.-Model-Approaches-—-Overview) — All four models + ablation described before training
  - [4a. Country Ranking Task](#4a.-Country-Ranking-Task) — Logistic Regression + XGBRanker
  - [4b. Timing Prediction Task](#4b.-Timing-Prediction-Task) — Linear Regression + XGBRegressor
  - [4c. Ablation: Pre-Filtering Gate](#4c.-Ablation:-Pre-Filtering-Gate-(Will-Spread-Classifier)) — Will-spread classifier

**Training**
- [5. Model Training](#5.-Model-Training) — All training code grouped together

**Results & Selection**
- [6. Results — How Does Each Model Perform?](#6.-Results-—-How-Does-Each-Model-Perform?)
  - [6a. Country Ranking Results](#6a.-Country-Ranking-Results) — Naive → LR → XGBRanker comparison
  - [6b. Timing Prediction Results](#6b.-Timing-Prediction-Results) — Linear Regression → XGBRegressor comparison
  - [6c. Ablation: Gate vs No Gate](#6c.-Ablation:-Gate-vs-No-Gate) — Recall-cost tradeoff analysis
- [7. Model Selection — Which Do We Choose?](#7.-Model-Selection-—-Which-Do-We-Choose?) — Business-driven final model choice

**Wrap-up**
- [8. Visualizations](#8.-Visualizations) — Feature importance, coefficients, calibration, bootstrap plots
- [9. Artifact Export](#9.-Artifact-Export) — Model files, evaluation parquets, training summary
- [10. Conclusion](#10.-Conclusion) — Key findings, performance ladder, business impact, limitations

In [ ]:
from pathlib import Path
import json
import os
import pickle
import tempfile
import warnings

os.environ.setdefault('MPLCONFIGDIR', tempfile.mkdtemp(prefix='matplotlib-'))

import duckdb
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import optuna
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    average_precision_score,
    brier_score_loss,
    f1_score,
    fbeta_score,
    log_loss,
    mean_absolute_error,
    mean_squared_error,
    median_absolute_error,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
)
from IPython.display import display
import xgboost as xgb

optuna.logging.set_verbosity(optuna.logging.INFO)
warnings.filterwarnings('ignore', category=FutureWarning)
pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 240)


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'datasets').exists() and (candidate / 'requirements.txt').exists():
            return candidate
    raise FileNotFoundError(
        f"Could not locate project root from {start}. Expected a parent containing 'datasets/' and 'requirements.txt'."
    )


ROOT = find_project_root(Path.cwd().resolve())
DATA_DIR = ROOT / 'datasets' / 'v3_features'
MODEL_DIR = ROOT / 'artifacts' / 'models' / 'xgboost_final_pipeline'
EVAL_DIR = ROOT / 'artifacts' / 'evaluations' / 'xgboost_final_pipeline'
MODEL_DIR.mkdir(parents=True, exist_ok=True)
EVAL_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = DATA_DIR / 'train.parquet'
VAL_PATH = DATA_DIR / 'val.parquet'
TEST_PATH = DATA_DIR / 'test.parquet'

assert TRAIN_PATH.exists(), f'Missing training split: {TRAIN_PATH}'
assert VAL_PATH.exists(), f'Missing validation split: {VAL_PATH}'
assert TEST_PATH.exists(), f'Missing test split: {TEST_PATH}'

# --- Config ---
RANDOM_STATE = 42
TOP_K = 5

RANKER_N_TRIALS = 50
CLASSIFIER_N_TRIALS = 30
REGRESSOR_N_TRIALS = 30

TIME_BLOCKS = 5
OPTUNA_N_STARTUP_TRIALS = 10
EARLY_STOPPING_ROUNDS = 50
TUNING_N_ESTIMATORS = 2000
FINAL_N_ESTIMATOR_BUFFER = 1.10

PRIMARY_PRECISION_FLOOR = 0.20
BUSINESS_PRECISION_FLOORS = [0.20, 0.25]

# Prior-notebook artifact paths (for feature selection + comparison)
NB09_EVAL_DIR = ROOT / 'artifacts' / 'evaluations' / 'xgboost_ranker_temporal_tuned'
NB10_EVAL_DIR = ROOT / 'artifacts' / 'evaluations' / 'xgboost_will_spread_classifier'

print({
    'ranker_n_trials': RANKER_N_TRIALS,
    'classifier_n_trials': CLASSIFIER_N_TRIALS,
    'regressor_n_trials': REGRESSOR_N_TRIALS,
    'time_blocks': TIME_BLOCKS,
    'top_k': TOP_K,
})

## 1. Setup and Helper Functions

All shared utilities for data loading, temporal cross-validation, ranking metrics, and model fitting.

### Temporal Train/Validation/Test Split

We split data by the track's first chart date: **train ≤ 2019, validation = 2020, test = 2021**. This strict temporal split is essential because:

- **Preventing data leakage:** Random k-fold CV would allow the model to train on 2021 tracks and predict 2019 tracks — an impossible scenario in production where we only have historical data. Music trends, artist popularity, and platform dynamics evolve over time; a model must prove it generalizes *forward*.
- **Why full calendar years?** Music diffusion is seasonal (holiday releases, summer hits, award season). Year-level splits ensure each split contains a full seasonal cycle, avoiding bias from partial-year effects. Finer splits (e.g., monthly) would introduce boundary artifacts where a track's 60-day prediction horizon crosses the split boundary.
- **Temporal CV within training:** During hyperparameter tuning, we further split the training set (≤2019) into 3 expanding-window folds using `make_temporal_folds()` (5 time blocks → 3 folds). Each fold trains on earlier blocks and validates on the next, maintaining temporal ordering even within the training set.

In [16]:
con = duckdb.connect()

FEATURE_EXCLUDE = ['track_id', 'observation_time', 'target_country', 'did_enter_within_60d', 'days_to_entry']
TARGET_SPECIFIC_COLS = [
    'artist_prior_success_in_target',
    'target_population',
    'target_avg_daily_streams',
    'target_new_entry_rate_30d',
    'target_continent_africa',
    'target_continent_asia',
    'target_continent_europe',
    'target_continent_north_america',
    'target_continent_oceania',
    'target_continent_south_america',
    'cultural_dist_min',
    'cultural_dist_missing',
    'same_language_flag',
    'same_continent_flag',
    'neighbor_entered_count',
]
EXCLUDE_FROM_TRACK_LEVEL = {'target_country', 'did_enter_within_60d', 'days_to_entry'}


# ── Data loading ──────────────────────────────────────────────────────────────

def load_row_level_split(path: Path, max_tracks: int | None = None) -> pd.DataFrame:
    parquet_path = path.as_posix()
    if max_tracks is None:
        query = f"SELECT * FROM read_parquet('{parquet_path}')"
    else:
        query = f"""
            WITH sampled_tracks AS (
                SELECT track_id
                FROM read_parquet('{parquet_path}')
                GROUP BY track_id
                ORDER BY hash(track_id)
                LIMIT {int(max_tracks)}
            )
            SELECT d.*
            FROM read_parquet('{parquet_path}') d
            JOIN sampled_tracks st USING (track_id)
        """
    df = con.execute(query).fetchdf()
    df['observation_time'] = pd.to_datetime(df['observation_time'])
    return df


def load_track_level_split(path: Path, max_tracks: int | None = None) -> pd.DataFrame:
    parquet_path = path.as_posix()
    schema_df = con.execute(f"SELECT * FROM read_parquet('{parquet_path}') LIMIT 0").fetchdf()
    raw_cols = list(schema_df.columns)
    constant_cols = [c for c in raw_cols if c not in EXCLUDE_FROM_TRACK_LEVEL and c not in TARGET_SPECIFIC_COLS]
    rank_cols = [c for c in raw_cols if c.startswith('rank_')]

    source_expr = f"read_parquet('{parquet_path}')"
    if max_tracks is None:
        source_query = source_expr
    else:
        source_query = f"""
            (
                WITH sampled_tracks AS (
                    SELECT track_id
                    FROM {source_expr}
                    GROUP BY track_id
                    ORDER BY hash(track_id)
                    LIMIT {int(max_tracks)}
                )
                SELECT d.*
                FROM {source_expr} d
                JOIN sampled_tracks st USING (track_id)
            )
        """

    select_parts = [
        'track_id',
        'MAX(CAST(did_enter_within_60d AS INTEGER)) AS will_spread',
        'MIN(CASE WHEN did_enter_within_60d = 1 THEN days_to_entry END) AS min_days_to_spread',
        'COUNT(*) AS candidate_count',
    ]
    select_parts.extend([f'ANY_VALUE({col}) AS {col}' for col in constant_cols if col != 'track_id'])
    for col in TARGET_SPECIFIC_COLS:
        select_parts.append(f'AVG({col}) AS {col}_mean')
        select_parts.append(f'MAX({col}) AS {col}_max')

    query = f"""
        SELECT
            {', '.join(select_parts)}
        FROM {source_query}
        GROUP BY track_id
        ORDER BY track_id
    """
    df = con.execute(query).fetchdf()
    df['observation_time'] = pd.to_datetime(df['observation_time'])
    df['origin_country_count_at_obs'] = (df[rank_cols].fillna(0) > 0).sum(axis=1)
    return df


def make_feature_matrix(df: pd.DataFrame, feature_cols: list[str], fill_values: pd.Series) -> pd.DataFrame:
    return df[feature_cols].copy().fillna(fill_values)


# ── Temporal CV ───────────────────────────────────────────────────────────────

def make_temporal_folds(df: pd.DataFrame, time_blocks: int = 5) -> list[dict]:
    track_times = df[['track_id', 'observation_time']].drop_duplicates().sort_values(
        ['observation_time', 'track_id']
    ).reset_index(drop=True)
    track_times['time_block'] = pd.qcut(track_times.index, q=time_blocks, labels=False, duplicates='drop')
    folds = []
    unique_blocks = sorted(track_times['time_block'].dropna().astype(int).unique())
    for fold_idx, block in enumerate(unique_blocks[2:], start=1):
        train_track_ids = track_times.loc[track_times['time_block'] < block, 'track_id'].tolist()
        val_track_ids = track_times.loc[track_times['time_block'] == block, 'track_id'].tolist()
        if not train_track_ids or not val_track_ids:
            continue
        train_times = track_times.loc[track_times['time_block'] < block, 'observation_time']
        val_times = track_times.loc[track_times['time_block'] == block, 'observation_time']
        folds.append({
            'fold': fold_idx,
            'train_track_ids': train_track_ids,
            'val_track_ids': val_track_ids,
            'train_tracks': len(train_track_ids),
            'val_tracks': len(val_track_ids),
            'train_start': str(train_times.min().date()),
            'train_end': str(train_times.max().date()),
            'val_start': str(val_times.min().date()),
            'val_end': str(val_times.max().date()),
        })
    return folds


# ── Metrics ───────────────────────────────────────────────────────────────────

def safe_roc_auc(y_true, y_score) -> float | None:
    y_true = np.asarray(y_true)
    if len(np.unique(y_true)) < 2:
        return None
    return float(roc_auc_score(y_true, y_score))


def safe_average_precision(y_true, y_score) -> float | None:
    y_true = np.asarray(y_true)
    if len(np.unique(y_true)) < 2:
        return None
    return float(average_precision_score(y_true, y_score))


def binary_metrics(y_true, y_score) -> dict:
    clipped = np.clip(y_score, 1e-6, 1 - 1e-6)
    return {
        'roc_auc': safe_roc_auc(y_true, y_score),
        'average_precision': safe_average_precision(y_true, y_score),
        'log_loss': float(log_loss(y_true, clipped, labels=[0, 1])),
    }


def build_threshold_table(y_true, y_prob, beta: float = 2.0) -> pd.DataFrame:
    precision, recall, thresholds = precision_recall_curve(y_true, y_prob)
    rows = []
    beta_sq = beta ** 2
    for p, r, t in zip(precision[:-1], recall[:-1], thresholds):
        denom = p + r
        f1 = 0.0 if denom == 0 else 2 * p * r / denom
        fbeta = 0.0 if (beta_sq * p + r) == 0 else (1 + beta_sq) * p * r / (beta_sq * p + r)
        predicted_positive_rate = float((y_prob >= t).mean())
        rows.append({
            'threshold': float(t),
            'precision': float(p),
            'recall': float(r),
            'f1': float(f1),
            f'f{beta}': float(fbeta),
            'predicted_positive_rate': predicted_positive_rate,
            'flagged_per_1000_tracks': predicted_positive_rate * 1000.0,
        })
    return pd.DataFrame(rows).sort_values(['threshold']).reset_index(drop=True)


def choose_recall_threshold(y_true, y_prob, precision_floor: float, beta: float = 2.0):
    threshold_df = build_threshold_table(y_true, y_prob, beta=beta)
    eligible = threshold_df[threshold_df['precision'] >= precision_floor].copy()
    if not eligible.empty:
        selected = eligible.sort_values(['recall', 'precision', 'threshold'], ascending=[False, False, True]).iloc[0]
        reason = f'highest recall with precision >= {precision_floor:.2f}'
    else:
        score_col = f'f{beta}'
        selected = threshold_df.sort_values([score_col, 'recall', 'precision'], ascending=[False, False, False]).iloc[0]
        reason = f'fallback to best {score_col} because no threshold met precision floor {precision_floor:.2f}'
    return float(selected['threshold']), threshold_df, reason


def binary_summary(y_true, y_prob, threshold: float, beta: float = 2.0) -> dict:
    y_pred = (y_prob >= threshold).astype(int)
    clipped = np.clip(y_prob, 1e-6, 1 - 1e-6)
    return {
        'roc_auc': safe_roc_auc(y_true, y_prob),
        'average_precision': safe_average_precision(y_true, y_prob),
        'log_loss': float(log_loss(y_true, clipped, labels=[0, 1])),
        'brier_score': float(brier_score_loss(y_true, clipped)),
        'precision': float(precision_score(y_true, y_pred, zero_division=0)),
        'recall': float(recall_score(y_true, y_pred, zero_division=0)),
        'f1': float(f1_score(y_true, y_pred, zero_division=0)),
        f'f{beta}': float(fbeta_score(y_true, y_pred, beta=beta, zero_division=0)),
        'positive_rate': float(np.mean(y_true)),
        'predicted_positive_rate': float(np.mean(y_pred)),
        'flagged_per_1000_tracks': float(np.mean(y_pred) * 1000.0),
    }


def build_business_threshold_summary(y_true, y_prob, floors: list[float], beta: float = 2.0):
    rows = []
    threshold_tables = []
    threshold_map = {}
    for floor in floors:
        threshold, threshold_df, reason = choose_recall_threshold(y_true, y_prob, precision_floor=floor, beta=beta)
        metrics = binary_summary(y_true, y_prob, threshold=threshold, beta=beta)
        rows.append({
            'precision_floor': float(floor),
            'threshold': float(threshold),
            'selection_reason': reason,
            **metrics,
        })
        threshold_map[float(floor)] = float(threshold)
        threshold_df = threshold_df.copy()
        threshold_df['precision_floor'] = float(floor)
        threshold_tables.append(threshold_df)
    return pd.DataFrame(rows), threshold_map, pd.concat(threshold_tables, ignore_index=True)


def compute_candidate_stats(scored_df: pd.DataFrame) -> dict:
    per_track = scored_df.groupby('track_id').agg(
        candidates=('target_country', 'size'),
        positives=('did_enter_within_60d', 'sum'),
    )
    positive_mask = per_track['positives'] > 0
    return {
        'tracks': int(per_track.shape[0]),
        'positive_tracks': int(positive_mask.sum()),
        'avg_candidates_per_track': float(per_track['candidates'].mean()),
        'avg_future_countries_per_track': float(per_track['positives'].mean()),
        'avg_future_countries_per_positive_track': float(per_track.loc[positive_mask, 'positives'].mean()) if positive_mask.any() else None,
    }


def ranking_metrics(scored_df: pd.DataFrame, k: int = 5) -> tuple[dict, pd.DataFrame]:
    rows = []
    for track_id, group in scored_df.groupby('track_id', sort=False):
        group = group.sort_values(['score', 'tie_break'], ascending=[False, False]).reset_index(drop=True)
        labels = group['did_enter_within_60d'].to_numpy(dtype=int)
        positives = int(labels.sum())
        top = group.head(k)
        top_labels = top['did_enter_within_60d'].to_numpy(dtype=int)
        hits = int(top_labels.sum())

        precision = hits / k
        recall = hits / positives if positives else np.nan
        hit_rate = float(hits > 0) if positives else np.nan

        discounts = np.log2(np.arange(2, len(top_labels) + 2))
        dcg = float(((2 ** top_labels - 1) / discounts).sum())
        ideal = np.sort(labels)[::-1][:len(top_labels)]
        idcg = float(((2 ** ideal - 1) / np.log2(np.arange(2, len(ideal) + 2))).sum())
        ndcg = dcg / idcg if idcg > 0 else np.nan

        ap_accum = 0.0
        running_hits = 0
        for rank, rel in enumerate(top_labels, start=1):
            if rel:
                running_hits += 1
                ap_accum += running_hits / rank
        map_k = ap_accum / min(positives, k) if positives else np.nan

        rows.append({
            'track_id': track_id,
            'positives': positives,
            'top_k_hits': hits,
            f'precision@{k}': precision,
            f'recall@{k}': recall,
            f'hit_rate@{k}': hit_rate,
            f'ndcg@{k}': ndcg,
            f'map@{k}': map_k,
        })

    metric_df = pd.DataFrame(rows)
    positive_mask = metric_df['positives'] > 0
    summary = {
        'tracks': int(metric_df.shape[0]),
        'positive_tracks': int(positive_mask.sum()),
        f'precision@{k}': float(metric_df[f'precision@{k}'].mean()),
        f'recall@{k}': float(metric_df.loc[positive_mask, f'recall@{k}'].mean()) if positive_mask.any() else None,
        f'hit_rate@{k}': float(metric_df.loc[positive_mask, f'hit_rate@{k}'].mean()) if positive_mask.any() else None,
        f'ndcg@{k}': float(metric_df.loc[positive_mask, f'ndcg@{k}'].mean()) if positive_mask.any() else None,
        f'map@{k}': float(metric_df.loc[positive_mask, f'map@{k}'].mean()) if positive_mask.any() else None,
        'mean_future_countries_per_track': float(metric_df['positives'].mean()),
    }
    return summary, metric_df


def evaluate_ranked_candidates(scored_df: pd.DataFrame, k: int = 5) -> tuple[dict, pd.DataFrame]:
    candidate_stats = compute_candidate_stats(scored_df)
    binary = binary_metrics(scored_df['did_enter_within_60d'], scored_df['score'].to_numpy())
    ranking_all, track_metrics = ranking_metrics(scored_df, k=k)
    positive_track_metrics = track_metrics[track_metrics['positives'] > 0].copy()
    positive_summary = {
        'tracks': int(positive_track_metrics.shape[0]),
        'avg_future_countries_per_positive_track': float(positive_track_metrics['positives'].mean()) if not positive_track_metrics.empty else None,
        f'avg_top_{k}_hits_per_positive_track': float(positive_track_metrics['top_k_hits'].mean()) if not positive_track_metrics.empty else None,
        f'recall@{k}': float(positive_track_metrics[f'recall@{k}'].mean()) if not positive_track_metrics.empty else None,
        f'hit_rate@{k}': float(positive_track_metrics[f'hit_rate@{k}'].mean()) if not positive_track_metrics.empty else None,
        f'ndcg@{k}': float(positive_track_metrics[f'ndcg@{k}'].mean()) if not positive_track_metrics.empty else None,
        f'map@{k}': float(positive_track_metrics[f'map@{k}'].mean()) if not positive_track_metrics.empty else None,
    }
    return {
        'binary': binary,
        'candidate_stats': candidate_stats,
        'ranking_all_tracks': ranking_all,
        'ranking_positive_tracks': positive_summary,
    }, track_metrics


def regression_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    abs_err = np.abs(y_true - y_pred)
    return {
        'mae': float(mean_absolute_error(y_true, y_pred)),
        'rmse': float(np.sqrt(mean_squared_error(y_true, y_pred))),
        'median_ae': float(median_absolute_error(y_true, y_pred)),
        'pct_within_3_days': float(np.mean(abs_err <= 3.0)),
        'pct_within_7_days': float(np.mean(abs_err <= 7.0)),
    }


# ── Scoring helpers ──────────────────────────────────────────────────────────

def normalize_scores(values: pd.Series) -> pd.Series:
    value_min = float(values.min())
    value_max = float(values.max())
    if value_max > value_min:
        return (values - value_min) / (value_max - value_min)
    return pd.Series(np.full(len(values), 0.5), index=values.index)


def score_naive_popularity(df: pd.DataFrame) -> pd.DataFrame:
    scored = df[['track_id', 'observation_time', 'target_country', 'did_enter_within_60d', 'days_to_entry', 'target_avg_daily_streams', 'target_new_entry_rate_30d']].copy()
    primary = scored['target_avg_daily_streams'].fillna(0.0)
    tie_break = scored['target_new_entry_rate_30d'].fillna(0.0)
    raw_score = primary + tie_break * 1e-6
    scored['score'] = normalize_scores(raw_score)
    scored['tie_break'] = tie_break
    scored['model_name'] = 'naive_popularity_baseline'
    return scored


def feature_category(name: str) -> str:
    if name.startswith('rank_') or name in {'track_in_viral50_at_obs', 'candidate_count', 'origin_country_count_at_obs'}:
        return 'current_footprint'
    if name.startswith('artist_') or name == 'multi_artist_flag':
        return 'artist_history'
    if name.startswith('target_'):
        return 'target_country_priors'
    if name in {'cultural_dist_min', 'cultural_dist_missing', 'same_language_flag', 'same_continent_flag', 'neighbor_entered_count'}:
        return 'origin_target_relationship'
    if name.endswith('_mean') or name.endswith('_max'):
        return 'aggregates'
    if name.startswith('af_') or name in {'duration_ms', 'explicit', 'days_since_release', 'is_friday_release'}:
        return 'audio_track_metadata'
    if name.startswith('observation_'):
        return 'temporal'
    return 'other'


# ── Ranker helpers ────────────────────────────────────────────────────────────

def prepare_ranker_inputs(df: pd.DataFrame, feature_cols: list[str], fill_values: pd.Series):
    ordered = df.sort_values(['track_id', 'target_country']).reset_index(drop=True)
    X = make_feature_matrix(ordered, feature_cols, fill_values)
    y = ordered['did_enter_within_60d'].astype(float).to_numpy()
    group = ordered.groupby('track_id', sort=False).size().to_numpy()
    return ordered, X, y, group


def make_ranker(params: dict, n_estimators: int = TUNING_N_ESTIMATORS, early_stopping_rounds: int | None = EARLY_STOPPING_ROUNDS):
    init_kwargs = {
        'objective': 'rank:ndcg',
        'eval_metric': f'ndcg@{TOP_K}',
        'tree_method': 'hist',
        'n_estimators': n_estimators,
        'random_state': RANDOM_STATE,
        'n_jobs': -1,
        **params,
    }
    if early_stopping_rounds is not None:
        init_kwargs['early_stopping_rounds'] = early_stopping_rounds
    return xgb.XGBRanker(**init_kwargs)


def score_ranker(model, df: pd.DataFrame, feature_cols: list[str], fill_values: pd.Series, model_name: str) -> pd.DataFrame:
    ordered = df.sort_values(['track_id', 'target_country']).reset_index(drop=True)
    X = make_feature_matrix(ordered, feature_cols, fill_values)
    raw_scores = pd.Series(model.predict(X), index=ordered.index)
    scored = ordered[['track_id', 'observation_time', 'target_country', 'did_enter_within_60d', 'days_to_entry', 'target_avg_daily_streams', 'target_new_entry_rate_30d']].copy()
    scored['score'] = normalize_scores(raw_scores)
    scored['raw_score'] = raw_scores.to_numpy()
    scored['tie_break'] = scored['target_new_entry_rate_30d'].fillna(0.0)
    scored['model_name'] = model_name
    return scored


def fit_ranker_with_validation(train_part, val_part, feature_cols, fill_values, params):
    _, X_train, y_train, group_train = prepare_ranker_inputs(train_part, feature_cols, fill_values)
    _, X_val, y_val, group_val = prepare_ranker_inputs(val_part, feature_cols, fill_values)
    model = make_ranker(params)
    model.fit(X_train, y_train, group=group_train, eval_set=[(X_val, y_val)], eval_group=[group_val], verbose=False)
    return model


def fit_final_ranker(train_part, feature_cols, fill_values, params, n_estimators):
    _, X_train, y_train, group_train = prepare_ranker_inputs(train_part, feature_cols, fill_values)
    model = make_ranker(params, n_estimators=n_estimators, early_stopping_rounds=None)
    model.fit(X_train, y_train, group=group_train, verbose=False)
    return model


# ── Regressor helpers ─────────────────────────────────────────────────────────

def transform_target(y, target_transform: str) -> np.ndarray:
    y_arr = np.asarray(y, dtype=float)
    if target_transform == 'log1p':
        return np.log1p(y_arr)
    if target_transform == 'sqrt':
        return np.sqrt(y_arr)
    return y_arr


def inverse_transform_target(y: np.ndarray, target_transform: str) -> np.ndarray:
    y_arr = np.asarray(y, dtype=float)
    if target_transform == 'log1p':
        return np.expm1(y_arr)
    if target_transform == 'sqrt':
        return np.square(y_arr)
    return y_arr


def make_regressor(params: dict, n_estimators: int = 800, early_stopping_rounds: int | None = 30):
    init_kwargs = {
        'objective': 'reg:squarederror',
        'eval_metric': 'mae',
        'tree_method': 'hist',
        'n_estimators': n_estimators,
        'random_state': RANDOM_STATE,
        'n_jobs': -1,
        **params,
    }
    if early_stopping_rounds is not None:
        init_kwargs['early_stopping_rounds'] = early_stopping_rounds
    return xgb.XGBRegressor(**init_kwargs)


def score_regressor(model, df, feature_cols, fill_values, target_transform='identity'):
    preds = model.predict(make_feature_matrix(df, feature_cols, fill_values))
    preds = inverse_transform_target(preds, target_transform)
    scored = df[['track_id', 'observation_time', 'target_country', 'did_enter_within_60d', 'days_to_entry']].copy()
    scored['predicted_days_to_entry'] = np.clip(preds, 1.0, 60.0)
    return scored


# ── Pipeline integration helpers ──────────────────────────────────────────────

def add_stage1_to_row_predictions(row_scored_df, stage1_scored_df, threshold_map):
    merged = row_scored_df.merge(
        stage1_scored_df[['track_id', 'score']].rename(columns={'score': 'spread_score'}),
        on='track_id', how='left',
    )
    for floor, threshold in threshold_map.items():
        col = f'spread_decision_floor_{float(floor):.2f}'.replace('.', '_')
        merged[col] = (merged['spread_score'] >= float(threshold)).astype(int)
    return merged


def add_regression_predictions(row_scored_df, reg_scored_df):
    return row_scored_df.merge(
        reg_scored_df[['track_id', 'target_country', 'predicted_days_to_entry']],
        on=['track_id', 'target_country'], how='left',
    )


def add_predicted_rank(scored_df):
    ranked = scored_df.sort_values(['track_id', 'score', 'target_new_entry_rate_30d'], ascending=[True, False, False]).copy()
    ranked['predicted_rank'] = ranked.groupby('track_id').cumcount().add(1).astype(int)
    return ranked


def evaluate_gated_pipeline(scored_df, gate_col, k=5):
    rows = []
    hit_rows = []
    topk_rows = []
    for track_id, group in scored_df.groupby('track_id', sort=False):
        group = group.sort_values(['score', 'target_new_entry_rate_30d'], ascending=[False, False]).reset_index(drop=True)
        labels = group['did_enter_within_60d'].to_numpy(dtype=int)
        positives = int(labels.sum())
        gated = bool(group[gate_col].iloc[0]) if not group.empty else False
        top = group.head(k).copy() if gated else group.head(0).copy()
        top_labels = top['did_enter_within_60d'].to_numpy(dtype=int)
        hits = int(top_labels.sum())

        precision = hits / k
        recall = hits / positives if positives else np.nan
        hit_rate = float(hits > 0) if positives else np.nan

        discounts = np.log2(np.arange(2, len(top_labels) + 2)) if len(top_labels) else np.array([])
        dcg = float(((2 ** top_labels - 1) / discounts).sum()) if len(top_labels) else 0.0
        ideal = np.sort(labels)[::-1][:k]
        idcg = float(((2 ** ideal - 1) / np.log2(np.arange(2, len(ideal) + 2))).sum()) if positives else 0.0
        ndcg = dcg / idcg if idcg > 0 else np.nan

        ap_accum = 0.0
        running_hits = 0
        for rank, rel in enumerate(top_labels, start=1):
            if rel:
                running_hits += 1
                ap_accum += running_hits / rank
        map_k = ap_accum / min(positives, k) if positives else np.nan

        rows.append({
            'track_id': track_id, 'positives': positives, 'stage1_flagged': int(gated),
            'top_k_hits': hits, f'precision@{k}': precision, f'recall@{k}': recall,
            f'hit_rate@{k}': hit_rate, f'ndcg@{k}': ndcg, f'map@{k}': map_k,
        })
        if not top.empty:
            topk_rows.append(top)
            hits_df = top[top['did_enter_within_60d'] == 1].copy()
            if not hits_df.empty:
                hit_rows.append(hits_df)

    metric_df = pd.DataFrame(rows)
    positive_mask = metric_df['positives'] > 0
    summary = {
        'tracks': int(metric_df.shape[0]),
        'positive_tracks': int(positive_mask.sum()),
        'flagged_tracks': int(metric_df['stage1_flagged'].sum()),
        f'precision@{k}': float(metric_df[f'precision@{k}'].mean()),
        f'recall@{k}': float(metric_df.loc[positive_mask, f'recall@{k}'].mean()) if positive_mask.any() else None,
        f'hit_rate@{k}': float(metric_df.loc[positive_mask, f'hit_rate@{k}'].mean()) if positive_mask.any() else None,
        f'ndcg@{k}': float(metric_df.loc[positive_mask, f'ndcg@{k}'].mean()) if positive_mask.any() else None,
        f'map@{k}': float(metric_df.loc[positive_mask, f'map@{k}'].mean()) if positive_mask.any() else None,
    }
    topk_df = pd.concat(topk_rows, ignore_index=True) if topk_rows else scored_df.head(0).copy()
    hit_df = pd.concat(hit_rows, ignore_index=True) if hit_rows else scored_df.head(0).copy()
    if not hit_df.empty:
        day_metrics = regression_metrics(hit_df['days_to_entry'].astype(float).to_numpy(), hit_df['predicted_days_to_entry'].astype(float).to_numpy())
        day_metrics['evaluated_rows'] = int(len(hit_df))
    else:
        day_metrics = {'mae': None, 'rmse': None, 'median_ae': None, 'pct_within_3_days': None, 'pct_within_7_days': None, 'evaluated_rows': 0}
    return summary, metric_df, day_metrics, topk_df


print('All helper functions defined.')


def fit_regressor_with_validation(train_pos, val_pos, feature_cols, fill_values, params, target_transform='identity'):
    X_train = make_feature_matrix(train_pos, feature_cols, fill_values)
    y_train = transform_target(train_pos['days_to_entry'].astype(float), target_transform)
    X_val = make_feature_matrix(val_pos, feature_cols, fill_values)
    y_val = transform_target(val_pos['days_to_entry'].astype(float), target_transform)
    model = make_regressor(params)
    model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)
    return model


def fit_final_regressor(train_pos, feature_cols, fill_values, params, n_estimators, target_transform='identity'):
    X_train = make_feature_matrix(train_pos, feature_cols, fill_values)
    y_train = transform_target(train_pos['days_to_entry'].astype(float), target_transform)
    model = make_regressor(params, n_estimators=n_estimators, early_stopping_rounds=None)
    model.fit(X_train, y_train, verbose=False)
    return model


All helper functions defined.


In [17]:
# ── Load data ─────────────────────────────────────────────────────────────────

row_train_df = load_row_level_split(TRAIN_PATH)
row_val_df = load_row_level_split(VAL_PATH)
row_test_df = load_row_level_split(TEST_PATH)

track_train_df = load_track_level_split(TRAIN_PATH)
track_val_df = load_track_level_split(VAL_PATH)
track_test_df = load_track_level_split(TEST_PATH)

# Row-level features (one row per track x target_country pair)
row_feature_cols = [col for col in row_train_df.columns if col not in FEATURE_EXCLUDE]
row_fill_values_train = row_train_df[row_feature_cols].median(numeric_only=True)
row_fill_values_final = pd.concat([row_train_df, row_val_df], ignore_index=True)[row_feature_cols].median(numeric_only=True)

# Track-level features (one row per track, for the classifier ablation)
track_feature_exclude = ['track_id', 'observation_time', 'will_spread', 'min_days_to_spread']
track_feature_cols = [col for col in track_train_df.columns if col not in track_feature_exclude]
track_fill_values = track_train_df[track_feature_cols].median(numeric_only=True)

# Temporal CV folds: 5 time blocks → 3 expanding-window folds (shared across all stages)
time_folds = make_temporal_folds(row_train_df, time_blocks=TIME_BLOCKS)

# Positive rows for the days-to-entry regressor
positive_train_rows = row_train_df[(row_train_df['did_enter_within_60d'] == 1) & row_train_df['days_to_entry'].notna()].copy()
positive_val_rows = row_val_df[(row_val_df['did_enter_within_60d'] == 1) & row_val_df['days_to_entry'].notna()].copy()
positive_test_rows = row_test_df[(row_test_df['did_enter_within_60d'] == 1) & row_test_df['days_to_entry'].notna()].copy()

# ── Summary ───────────────────────────────────────────────────────────────────
train_tracks = row_train_df['track_id'].nunique()
val_tracks = row_val_df['track_id'].nunique()
test_tracks = row_test_df['track_id'].nunique()
spread_rate = track_train_df['will_spread'].mean() * 100

print('=== Dataset Overview ===')
print(f'Temporal split: train (2017-2019) → val (2020) → test (2021)')
print(f'  Train: {len(row_train_df):>10,} rows | {train_tracks:>6,} tracks')
print(f'  Val:   {len(row_val_df):>10,} rows | {val_tracks:>6,} tracks')
print(f'  Test:  {len(row_test_df):>10,} rows | {test_tracks:>6,} tracks')
print(f'  Features: {len(row_feature_cols)} per (track, country) pair')
print()
print(f'Only {spread_rate:.1f}% of tracks spread to at least one new country within 60 days.')
print(f'Spreading tracks enter {track_train_df.loc[track_train_df["will_spread"]==1, "candidate_count"].mean():.0f} candidate markets on average.')
print()
print('Temporal CV folds (training data only):')
display(pd.DataFrame([{k: v for k, v in f.items() if k not in ('train_track_ids', 'val_track_ids')} for f in time_folds]))

=== Dataset Overview ===
Temporal split: train (2017-2019) → val (2020) → test (2021)
  Train:    272,922 rows | 64,093 tracks
  Val:    1,647,221 rows | 25,858 tracks
  Test:   1,535,867 rows | 24,047 tracks
  Features: 103 per (track, country) pair

Only 12.5% of tracks spread to at least one new country within 60 days.
Spreading tracks enter 9 candidate markets on average.

Temporal CV folds (training data only):


,fold,train_tracks,val_tracks,train_start,train_end,val_start,val_end
0,1,25637,12819,2017-01-01,2018-04-06,2018-04-06,2018-11-16
1,2,38456,12818,2017-01-01,2018-11-16,2018-11-16,2019-06-21
2,3,51274,12819,2017-01-01,2019-06-21,2019-06-21,2019-12-31


## 2. Feature Selection

Our feature matrix contains ~102 features per (track, target_country) pair, covering cultural distance, geographic proximity, artist history, chart momentum, and temporal patterns. Not all features contribute equally — prior experiments revealed that many small-country rank columns and niche cultural indicators carry zero predictive gain.

Specifically, we reuse the feature importance outputs from two development notebooks: **Notebook 09** (`xgboost_ranker_temporal_tuned`) trained an XGBRanker with temporal cross-validation on the country-ranking task, and **Notebook 10** (`xgboost_will_spread_classifier`) trained an XGBClassifier on the binary will-spread prediction task. Both exported per-feature gain scores after full training runs. Features that received exactly zero gain in these experiments — meaning the model never selected them for a split — are pruned here. For the row-level ranker this removes 2 features (`rank_andorra`, `target_continent_antarctica`); for the track-level classifier it removes 7 features (additional small-market rank columns like `rank_egypt`, `rank_morocco`, `rank_united_arab_emirates` and rare categorical flags like `cultural_dist_missing_max`).

We apply a **conservative pruning strategy**: remove only features where the trained model assigned exactly zero importance (gain = 0). This eliminates noise dimensions without risking information loss, and reduces training time for hyperparameter optimization.

In [18]:
# ── Row-level feature pruning (Stage 2 ranker) ───────────────────────────────
nb09_importance_path = NB09_EVAL_DIR / 'feature_importance.parquet'
assert nb09_importance_path.exists(), f'Missing NB09 importance: {nb09_importance_path}'

nb09_importance = con.execute(f"SELECT * FROM read_parquet('{nb09_importance_path.as_posix()}')").fetchdf()
zero_gain_row = nb09_importance[nb09_importance['gain'] == 0.0]['feature'].tolist()

pruned_row_feature_cols = [col for col in row_feature_cols if col not in zero_gain_row]
print(f'Row-level features: {len(row_feature_cols)} → {len(pruned_row_feature_cols)} (dropped {len(zero_gain_row)} zero-gain)')
print(f'Dropped: {zero_gain_row}')
print()

# ── Track-level feature pruning (Stage 1 classifier) ─────────────────────────
nb10_importance_path = NB10_EVAL_DIR / 'feature_importance.parquet'
assert nb10_importance_path.exists(), f'Missing NB10 importance: {nb10_importance_path}'

nb10_importance = con.execute(f"SELECT * FROM read_parquet('{nb10_importance_path.as_posix()}')").fetchdf()
zero_gain_track = nb10_importance[nb10_importance['gain'] == 0.0]['feature'].tolist()

pruned_track_feature_cols = [col for col in track_feature_cols if col not in zero_gain_track]
print(f'Track-level features: {len(track_feature_cols)} → {len(pruned_track_feature_cols)} (dropped {len(zero_gain_track)} zero-gain)')
print(f'Dropped: {zero_gain_track}')

# Update fill values to match pruned feature sets
pruned_row_fill_values_train = row_fill_values_train[pruned_row_feature_cols]
pruned_row_fill_values_final = row_fill_values_final[pruned_row_feature_cols]
pruned_track_fill_values = track_fill_values[pruned_track_feature_cols]

Row-level features: 103 → 101 (dropped 2 zero-gain)
Dropped: ['rank_andorra', 'target_continent_antarctica']

Track-level features: 120 → 113 (dropped 7 zero-gain)
Dropped: ['rank_andorra', 'rank_egypt', 'rank_morocco', 'rank_united_arab_emirates', 'target_continent_antarctica', 'target_continent_europe_max', 'cultural_dist_missing_max']


**Interpretation:** Feature pruning removed 2 row-level features (`rank_andorra`, `target_continent_antarctica`) from 103 → 101, and 7 track-level features from 120 → 113. These are zero-gain features — the model never found an informative split on them during training. `rank_andorra` reflects a market too small to carry predictive signal, while `target_continent_antarctica` is an artifact of the encoding with no real-world tracks. Removing them reduces noise and speeds up Optuna's hyperparameter search without sacrificing any predictive power. The remaining 101 features capture the most meaningful signals: cultural/geographic proximity, major-market chart positions, artist history, and temporal momentum.

## 3. Evaluation Metrics — Why These Metrics?

Before training any model, we define all evaluation metrics. This ensures that model development is guided by pre-specified criteria rather than post-hoc metric shopping.

### Ranking Metrics (Country Prediction Task)

- **recall@k:** "Of all countries a track actually charted in, what fraction appeared in our top-k?" — directly measures whether Spotify would target the right markets. We use k=5, aligned with the median spread of 5.17 countries.
- **ndcg@k (Normalized Discounted Cumulative Gain):** "Are the most relevant countries ranked higher?" — measures ranking quality, not just set membership. Important because marketing teams act on the *order* of predictions: the #1 predicted market gets more resources than #5.
- **hit_rate@k:** "For what fraction of tracks does at least one prediction hit?" — measures broad reliability across the track population.
- **MAP@k (Mean Average Precision):** Rewards placing correct countries earlier in the ranked list. Unlike ndcg, MAP uses binary relevance and averages precision at each relevant position.

### Timing Metrics (Days-to-Entry Prediction Task)

- **MAE (Mean Absolute Error):** Average days off — interpretable as "how many days is the prediction typically wrong?" Preferred over RMSE for business communication.
- **% within 3 days / 7 days:** Operationally meaningful thresholds — "can we plan a campaign around this prediction?" A prediction within 3 days enables tight coordination; within 7 days enables weekly planning cycles.

### Baselines

- **Naive popularity baseline (ranking):** Always predict the 5 globally most popular countries (by average daily streams). Any useful model must substantially outperform this.
- **Linear baselines (both tasks):** Logistic Regression for ranking, Linear Regression for timing. These establish what linear decision boundaries can capture, quantifying the value of non-linear modeling.

### Why Not Accuracy or F1?

With 110:1 class imbalance in the raw data (only ~0.9% of track×country pairs result in chart entry), a model predicting "no entry" everywhere achieves 99.1% accuracy. Similarly, F1 on the binary prediction conflates ranking quality with threshold selection. **Ranking metrics on the top-k** are far more meaningful for our use case: we always produce exactly k=5 predictions per track, and we care about the *set* and *order* of those predictions, not a binary decision boundary.

## 4. Model Approaches — Overview

This section describes all models before showing any results. We present two tasks (ranking and timing), each with a linear baseline and a gradient-boosted primary model, plus one ablation study.

### 4a. Country Ranking Task

**Logistic Regression (linear baseline):**
- StandardScaler + `class_weight='balanced'` to handle the ~16.7% positive rate in the downsampled training set
- Countries ranked by P(did_enter_within_60d = 1) — pointwise-to-ranking approach
- **Purpose:** (a) establishes what linear decision boundaries can capture (recall@5 ceiling with linear features), and (b) provides *directional* coefficient interpretation — e.g., "a one-standard-deviation increase in cultural distance *decreases* the log-odds of charting by X"

**XGBRanker (primary model):**
- `rank:ndcg` listwise objective — directly optimizes the ordering of candidate countries per track
- Optuna TPE sampler (50 trials) with temporal cross-validation (3 expanding-window folds)
- MedianPruner to early-stop unpromising trials after fold 1
- 8 hyperparameters: learning rate, max depth, min child weight, subsample, colsample, gamma, L1/L2 regularization
- **Purpose:** captures non-linear feature interactions (e.g., "high cultural distance BUT prior artist presence" may override the barrier)

### 4b. Timing Prediction Task

Both timing models are trained on **positive rows only** — tracks that actually entered the target country's chart. The regression target is `days_to_entry` (1–60 days).

**Linear Regression (linear baseline):**
- StandardScaler, trained on positive rows
- **Purpose:** establishes the linear ceiling for timing prediction; reveals which features linearly correlate with faster/slower spread (e.g., cultural proximity → faster entry)

**XGBRegressor (primary model):**
- Optuna-tuned with target transform selection (identity / log1p / sqrt) — the right-skewed distribution of days_to_entry benefits from variance-stabilizing transforms
- 30 trials with temporal CV on positive rows
- **Purpose:** captures non-linear timing patterns (e.g., culturally close markets are entered fast *only if* the artist has prior presence there)

### 4c. Ablation: Pre-Filtering Gate (Will-Spread Classifier)

A natural question: can a **pre-filtering gate** reduce inference cost by first predicting *whether* a track will spread, then only running the ranker on flagged tracks?

- XGBClassifier with isotonic calibration (to correct poorly-calibrated probabilities under 92.3% class imbalance)
- 30 Optuna trials with temporal CV
- Evaluated at multiple precision floors (0.20, 0.25) to quantify the recall-cost tradeoff
- **Hypothesis:** the gate will harm recall because filtering out tracks is inherently lossy — some tracks that spread to only 1–2 countries may be correctly classified as "unlikely to spread broadly" but still represent missed opportunities

## 5. Model Training

All training code is grouped in this section. Results interpretation follows in Section 6.

In [19]:
# ── Logistic Regression Baseline ──────────────────────────────────────────────

# Prepare features
X_train_lr = make_feature_matrix(row_train_df, pruned_row_feature_cols, pruned_row_fill_values_train)
y_train_lr = row_train_df['did_enter_within_60d'].to_numpy()

X_test_lr = make_feature_matrix(row_test_df, pruned_row_feature_cols, pruned_row_fill_values_final)
X_val_lr = make_feature_matrix(row_val_df, pruned_row_feature_cols, pruned_row_fill_values_train)

# Standardize features (fit on train only to prevent leakage)
lr_scaler = StandardScaler()
X_train_lr_scaled = lr_scaler.fit_transform(X_train_lr)
X_val_lr_scaled = lr_scaler.transform(X_val_lr)
X_test_lr_scaled = lr_scaler.transform(X_test_lr)

# Train logistic regression
lr_model = LogisticRegression(
    class_weight='balanced',
    max_iter=1000,
    solver='lbfgs',
    random_state=RANDOM_STATE,
    n_jobs=-1,
)
lr_model.fit(X_train_lr_scaled, y_train_lr)
print(f'Logistic Regression fitted: {lr_model.n_features_in_} features, converged in {lr_model.n_iter_[0]} iterations')

# Score validation and test sets — rank countries by P(spread)
def score_logistic_regression(model, scaler, df, feature_cols, fill_values, model_name):
    """Score a logistic regression model and format output for ranking evaluation."""
    ordered = df.sort_values(['track_id', 'target_country']).reset_index(drop=True)
    X = make_feature_matrix(ordered, feature_cols, fill_values)
    X_scaled = scaler.transform(X)
    proba = model.predict_proba(X_scaled)[:, 1]
    scored = ordered[['track_id', 'observation_time', 'target_country',
                       'did_enter_within_60d', 'days_to_entry',
                       'target_avg_daily_streams', 'target_new_entry_rate_30d']].copy()
    scored['score'] = normalize_scores(pd.Series(proba, index=ordered.index))
    scored['raw_score'] = proba
    scored['tie_break'] = scored['target_new_entry_rate_30d'].fillna(0.0)
    scored['model_name'] = model_name
    return scored

lr_val_scored = score_logistic_regression(
    lr_model, lr_scaler, row_val_df,
    pruned_row_feature_cols, pruned_row_fill_values_train, 'logistic_regression_val'
)
lr_test_scored = score_logistic_regression(
    lr_model, lr_scaler, row_test_df,
    pruned_row_feature_cols, pruned_row_fill_values_final, 'logistic_regression_test'
)

lr_val_results, _ = evaluate_ranked_candidates(lr_val_scored, k=TOP_K)
lr_test_results, _ = evaluate_ranked_candidates(lr_test_scored, k=TOP_K)

# ── Baseline comparison table ────────────────────────────────────────────────

baseline_test_scored = score_naive_popularity(row_test_df)
baseline_test_results, _ = evaluate_ranked_candidates(baseline_test_scored, k=TOP_K)

lr_comparison = pd.DataFrame([
    {'split': 'validation', 'model': 'logistic_regression',
     f'recall@{TOP_K}': lr_val_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': lr_val_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': lr_val_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': lr_val_results['ranking_all_tracks'][f'map@{TOP_K}']},
    {'split': 'test', 'model': 'logistic_regression',
     f'recall@{TOP_K}': lr_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': lr_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': lr_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': lr_test_results['ranking_all_tracks'][f'map@{TOP_K}']},
    {'split': 'test', 'model': 'naive_popularity',
     f'recall@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'map@{TOP_K}']},
])
print()
print('Baseline model comparison:')
display(lr_comparison)

Logistic Regression fitted: 101 features, converged in 27 iterations

Baseline model comparison:


,split,model,recall@5,ndcg@5,hit_rate@5,map@5
0,validation,logistic_regression,0.573333,0.586890,0.804183,0.518646
1,test,logistic_regression,0.581135,0.593875,0.809666,0.526138
2,test,naive_popularity,0.071285,0.105515,0.241654,0.078229


In [20]:
# ── Logistic Regression Feature Coefficients ─────────────────────────────────

# Extract coefficients (standardized — directly comparable across features)
lr_coef_df = pd.DataFrame({
    'feature': pruned_row_feature_cols,
    'coefficient': lr_model.coef_[0],
    'abs_coefficient': np.abs(lr_model.coef_[0]),
    'category': [feature_category(f) for f in pruned_row_feature_cols],
}).sort_values('abs_coefficient', ascending=False).reset_index(drop=True)

print('Top 20 most influential features (Logistic Regression, standardized coefficients):')
print('Positive = increases probability of charting in target country')
print('Negative = decreases probability of charting in target country')
print()
display(lr_coef_df.head(20)[['feature', 'coefficient', 'category']])

# Category-level summary: mean absolute coefficient per category
lr_category_summary = (
    lr_coef_df.groupby('category')['abs_coefficient']
    .agg(['mean', 'sum', 'count'])
    .sort_values('sum', ascending=False)
    .rename(columns={'mean': 'avg_abs_coef', 'sum': 'total_abs_coef', 'count': 'n_features'})
)
print()
print('Feature importance by category (Logistic Regression):')
display(lr_category_summary)

# ── Coefficient direction analysis for business interpretation ────────────────

print()
print('Key feature directions (business interpretation):')
key_features = [
    'cultural_dist_min', 'same_language_flag', 'same_continent_flag',
    'neighbor_entered_count', 'artist_prior_success_in_target',
    'target_avg_daily_streams', 'target_new_entry_rate_30d',
    'artist_prior_unique_regions', 'artist_country_ratio',
]
for feat in key_features:
    row = lr_coef_df[lr_coef_df['feature'] == feat]
    if not row.empty:
        coef = float(row['coefficient'].iloc[0])
        direction = 'increases' if coef > 0 else 'decreases'
        print(f'  {feat}: {coef:+.4f} → {direction} spread probability')

Top 20 most influential features (Logistic Regression, standardized coefficients):
Positive = increases probability of charting in target country
Negative = decreases probability of charting in target country



,feature,coefficient,category
0,artist_prior_unique_regions,0.851760,artist_history
1,same_language_flag,0.733400,origin_target_relationship
2,target_continent_europe,-0.647414,target_country_priors
3,artist_prior_success_in_target,0.608648,artist_history
4,target_continent_north_america,-0.561300,target_country_priors
5,target_continent_south_america,-0.557758,target_country_priors
6,target_continent_africa,-0.519434,target_country_priors
7,target_continent_asia,-0.456140,target_country_priors
8,artist_prior_best_rank,0.433217,artist_history
9,same_continent_flag,0.361888,origin_target_relationship



Feature importance by category (Logistic Regression):


,avg_abs_coef,total_abs_coef,n_features
category,,,
current_footprint,0.063118,4.165801,66
target_country_priors,0.379310,3.413794,9
artist_history,0.358386,2.508700,7
origin_target_relationship,0.287200,1.435998,5
audio_track_metadata,0.083523,1.002270,12
temporal,0.119039,0.238079,2



Key feature directions (business interpretation):
  cultural_dist_min: -0.1737 → decreases spread probability
  same_language_flag: +0.7334 → increases spread probability
  same_continent_flag: +0.3619 → increases spread probability
  neighbor_entered_count: +0.1013 → increases spread probability
  artist_prior_success_in_target: +0.6086 → increases spread probability
  target_avg_daily_streams: +0.0783 → increases spread probability
  target_new_entry_rate_30d: +0.1488 → increases spread probability
  artist_prior_unique_regions: +0.8518 → increases spread probability
  artist_country_ratio: +0.0992 → increases spread probability


In [21]:
# ── Optuna objective for Stage 2 ranker ────────────────────────────────────────

stage2_trial_records = []
stage2_fold_records = []


def ranker_objective(trial):
    params = {
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'max_depth': trial.suggest_int('max_depth', 4, 12),
        'min_child_weight': trial.suggest_float('min_child_weight', 1.0, 100.0, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.1, 20.0, log=True),
    }

    fold_ndcgs = []
    fold_summaries = []
    for fold_idx, fold in enumerate(time_folds):
        fold_train = row_train_df[row_train_df['track_id'].isin(fold['train_track_ids'])].copy()
        fold_val = row_train_df[row_train_df['track_id'].isin(fold['val_track_ids'])].copy()
        fold_fill = fold_train[pruned_row_feature_cols].median(numeric_only=True)

        _, X_train, y_train, group_train = prepare_ranker_inputs(fold_train, pruned_row_feature_cols, fold_fill)
        _, X_val, y_val, group_val = prepare_ranker_inputs(fold_val, pruned_row_feature_cols, fold_fill)

        model = make_ranker(params)
        model.fit(X_train, y_train, group=group_train,
                  eval_set=[(X_val, y_val)], eval_group=[group_val], verbose=False)

        scored_val = score_ranker(model, fold_val, pruned_row_feature_cols, fold_fill, 'xgb_ranker_fold')
        summary, _ = evaluate_ranked_candidates(scored_val, k=TOP_K)
        best_iter = getattr(model, 'best_iteration', None)
        resolved_rounds = int(best_iter + 1) if best_iter is not None else TUNING_N_ESTIMATORS

        ndcg = summary['ranking_all_tracks'][f'ndcg@{TOP_K}']
        fold_ndcgs.append(ndcg)

        fold_record = {
            'trial_label': f'optuna_{trial.number:03d}',
            'fold': fold['fold'],
            'best_iteration': resolved_rounds,
            f'ndcg@{TOP_K}': ndcg,
            f'recall@{TOP_K}': summary['ranking_all_tracks'][f'recall@{TOP_K}'],
            f'map@{TOP_K}': summary['ranking_all_tracks'][f'map@{TOP_K}'],
            'roc_auc': summary['binary']['roc_auc'],
        }
        fold_summaries.append(fold_record)
        stage2_fold_records.append(fold_record | params)

        # Report intermediate value for pruning
        trial.report(np.mean(fold_ndcgs), fold_idx)
        if trial.should_prune():
            raise optuna.TrialPruned()

    fold_df = pd.DataFrame(fold_summaries)
    record = {
        'trial_label': f'optuna_{trial.number:03d}',
        'mean_best_iteration': float(fold_df['best_iteration'].mean()),
        f'mean_ndcg@{TOP_K}': float(fold_df[f'ndcg@{TOP_K}'].mean()),
        f'mean_recall@{TOP_K}': float(fold_df[f'recall@{TOP_K}'].mean()),
        f'mean_map@{TOP_K}': float(fold_df[f'map@{TOP_K}'].mean()),
        'mean_roc_auc': float(fold_df['roc_auc'].mean()),
        **params,
    }
    stage2_trial_records.append(record)
    return record[f'mean_ndcg@{TOP_K}']


stage2_study = optuna.create_study(
    direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_startup_trials=OPTUNA_N_STARTUP_TRIALS, n_warmup_steps=0),
)
stage2_study.optimize(ranker_objective, n_trials=RANKER_N_TRIALS, show_progress_bar=True)

stage2_best_params = stage2_study.best_params
stage2_trial_df = pd.DataFrame(stage2_trial_records).sort_values(f'mean_ndcg@{TOP_K}', ascending=False).reset_index(drop=True)
stage2_fold_df = pd.DataFrame(stage2_fold_records)

print(f'Best ranker params (ndcg@{TOP_K} = {stage2_study.best_value:.6f}):')
print(json.dumps(stage2_best_params, indent=2))
print()
print('Top 10 trials:')
display(stage2_trial_df.head(10))

[I 2026-03-15 21:51:08,259] A new study created in memory with name: no-name-9bfffdf3-45ea-4e36-aa63-49716423e538
Best trial: 0. Best value: 0.940587:   2%|▏         | 1/50 [00:25<20:40, 25.32s/it]

[I 2026-03-15 21:51:33,574] Trial 0 finished with value: 0.9405870435054225 and parameters: {'learning_rate': 0.02757359293934948, 'max_depth': 12, 'min_child_weight': 29.10635913133069, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.5780093202212182, 'gamma': 0.7799726016810132, 'reg_alpha': 0.00019517224641449495, 'reg_lambda': 9.842315738502599}. Best is trial 0 with value: 0.9405870435054225.


Best trial: 1. Best value: 0.940863:   4%|▍         | 2/50 [00:49<19:51, 24.81s/it]

[I 2026-03-15 21:51:58,039] Trial 1 finished with value: 0.9408628108774776 and parameters: {'learning_rate': 0.05092911283433821, 'max_depth': 10, 'min_child_weight': 1.0994335574766196, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.9162213204002109, 'gamma': 1.0616955533913808, 'reg_alpha': 0.0008111941985431928, 'reg_lambda': 0.26425260575499165}. Best is trial 1 with value: 0.9408628108774776.


Best trial: 1. Best value: 0.940863:   6%|▌         | 3/50 [01:15<19:42, 25.17s/it]

[I 2026-03-15 21:52:23,622] Trial 2 finished with value: 0.9391526339688133 and parameters: {'learning_rate': 0.02279379523765072, 'max_depth': 8, 'min_child_weight': 7.309539835912911, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.8059264473611898, 'gamma': 0.6974693032602092, 'reg_alpha': 0.0028888383623653178, 'reg_lambda': 0.6966418981413739}. Best is trial 1 with value: 0.9408628108774776.


Best trial: 3. Best value: 0.944569:   8%|▊         | 4/50 [01:46<21:09, 27.59s/it]

[I 2026-03-15 21:52:54,924] Trial 3 finished with value: 0.9445689904457429 and parameters: {'learning_rate': 0.03438586247938296, 'max_depth': 11, 'min_child_weight': 2.5081156860452323, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7962072844310213, 'gamma': 0.23225206359998862, 'reg_alpha': 0.1090747583515769, 'reg_lambda': 0.24682044079890128}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  10%|█         | 5/50 [02:07<18:57, 25.28s/it]

[I 2026-03-15 21:53:16,107] Trial 4 finished with value: 0.937942844729115 and parameters: {'learning_rate': 0.011926324174062874, 'max_depth': 12, 'min_child_weight': 85.3618986286683, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.6523068845866853, 'gamma': 0.48836057003191935, 'reg_alpha': 0.2637333993381525, 'reg_lambda': 1.0299214204601976}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  12%|█▏        | 6/50 [02:28<17:23, 23.71s/it]

[I 2026-03-15 21:53:36,775] Trial 5 finished with value: 0.9396758294979621 and parameters: {'learning_rate': 0.013916438390377948, 'max_depth': 8, 'min_child_weight': 1.1715937392307056, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.6293899908000085, 'gamma': 3.31261142176991, 'reg_alpha': 0.0036187233309596225, 'reg_lambda': 1.5728674194978582}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  14%|█▍        | 7/50 [02:52<17:04, 23.84s/it]

[I 2026-03-15 21:54:00,864] Trial 6 finished with value: 0.9346654439165593 and parameters: {'learning_rate': 0.04395225692486303, 'max_depth': 5, 'min_child_weight': 86.9299151113955, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9697494707820946, 'gamma': 4.474136752138244, 'reg_alpha': 0.09761125443110452, 'reg_lambda': 13.220877067405613}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  16%|█▌        | 8/50 [03:14<16:11, 23.14s/it]

[I 2026-03-15 21:54:22,504] Trial 7 finished with value: 0.9340234789473368 and parameters: {'learning_rate': 0.012707942999213693, 'max_depth': 5, 'min_child_weight': 1.231557172366602, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6943386448447411, 'gamma': 1.3567451588694794, 'reg_alpha': 1.3921548533046488, 'reg_lambda': 0.6620642015198966}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  18%|█▊        | 9/50 [03:35<15:28, 22.66s/it]

[I 2026-03-15 21:54:44,102] Trial 8 finished with value: 0.9394539530240982 and parameters: {'learning_rate': 0.021399549030176226, 'max_depth': 8, 'min_child_weight': 1.9135880487692298, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.5372753218398854, 'gamma': 4.9344346830025865, 'reg_alpha': 0.7264803074826723, 'reg_lambda': 0.28658321062461245}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  20%|██        | 10/50 [04:02<15:53, 23.84s/it]

[I 2026-03-15 21:55:10,599] Trial 9 finished with value: 0.9351249155647762 and parameters: {'learning_rate': 0.010150665434429315, 'max_depth': 11, 'min_child_weight': 25.92475660475159, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8856351733429728, 'gamma': 0.3702232586704518, 'reg_alpha': 0.006199100007802264, 'reg_lambda': 0.18476435128841198}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  22%|██▏       | 11/50 [04:08<11:59, 18.44s/it]

[I 2026-03-15 21:55:16,801] Trial 10 pruned. 


Best trial: 3. Best value: 0.944569:  24%|██▍       | 12/50 [04:30<12:26, 19.64s/it]

[I 2026-03-15 21:55:39,182] Trial 11 finished with value: 0.9411395369305132 and parameters: {'learning_rate': 0.058684940898778196, 'max_depth': 10, 'min_child_weight': 2.8271667436887347, 'subsample': 0.7784580597232836, 'colsample_bytree': 0.8991358530198217, 'gamma': 1.7939314875484835, 'reg_alpha': 0.00021832392921754964, 'reg_lambda': 2.899639582473491}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  26%|██▌       | 13/50 [04:54<12:50, 20.84s/it]

[I 2026-03-15 21:56:02,769] Trial 12 finished with value: 0.9399233857923411 and parameters: {'learning_rate': 0.0717724651436296, 'max_depth': 10, 'min_child_weight': 3.4196538382062744, 'subsample': 0.7853549589092494, 'colsample_bytree': 0.8483208431135417, 'gamma': 2.638894465150159, 'reg_alpha': 0.022055966549515135, 'reg_lambda': 3.6089316192885637}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  28%|██▊       | 14/50 [05:17<12:51, 21.44s/it]

[I 2026-03-15 21:56:25,595] Trial 13 finished with value: 0.9398014985110485 and parameters: {'learning_rate': 0.07377114647210442, 'max_depth': 9, 'min_child_weight': 3.0103747815531356, 'subsample': 0.7993072627126802, 'colsample_bytree': 0.990490195064035, 'gamma': 1.840117785553761, 'reg_alpha': 0.00010405379083238518, 'reg_lambda': 3.6414844831057516}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  30%|███       | 15/50 [05:24<09:56, 17.04s/it]

[I 2026-03-15 21:56:32,435] Trial 14 pruned. 


Best trial: 3. Best value: 0.944569:  32%|███▏      | 16/50 [05:31<08:01, 14.17s/it]

[I 2026-03-15 21:56:39,942] Trial 15 pruned. 


Best trial: 3. Best value: 0.944569:  34%|███▍      | 17/50 [05:52<08:55, 16.24s/it]

[I 2026-03-15 21:57:01,008] Trial 16 finished with value: 0.9404891227480757 and parameters: {'learning_rate': 0.12666524992166675, 'max_depth': 11, 'min_child_weight': 2.2906050187559956, 'subsample': 0.8492392496965573, 'colsample_bytree': 0.9191904809865727, 'gamma': 1.6723494097694078, 'reg_alpha': 0.05786055456544665, 'reg_lambda': 1.7722292007534766}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  36%|███▌      | 18/50 [06:16<09:48, 18.40s/it]

[I 2026-03-15 21:57:24,433] Trial 17 finished with value: 0.9422393307806458 and parameters: {'learning_rate': 0.09713478796027722, 'max_depth': 6, 'min_child_weight': 5.143425320872166, 'subsample': 0.7663255107851121, 'colsample_bytree': 0.7505409072564342, 'gamma': 0.136095131955984, 'reg_alpha': 0.016082041627624794, 'reg_lambda': 0.43152733150603617}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  38%|███▊      | 19/50 [06:22<07:35, 14.69s/it]

[I 2026-03-15 21:57:30,491] Trial 18 pruned. 


Best trial: 3. Best value: 0.944569:  40%|████      | 20/50 [06:28<06:08, 12.29s/it]

[I 2026-03-15 21:57:37,182] Trial 19 pruned. 


Best trial: 3. Best value: 0.944569:  42%|████▏     | 21/50 [06:35<05:03, 10.47s/it]

[I 2026-03-15 21:57:43,395] Trial 20 pruned. 


Best trial: 3. Best value: 0.944569:  44%|████▍     | 22/50 [06:58<06:42, 14.36s/it]

[I 2026-03-15 21:58:06,833] Trial 21 finished with value: 0.9398212876613202 and parameters: {'learning_rate': 0.05289538268506832, 'max_depth': 9, 'min_child_weight': 5.212673661961979, 'subsample': 0.7632648351136759, 'colsample_bytree': 0.8593747658098843, 'gamma': 0.009057000263308884, 'reg_alpha': 0.0008139641813335736, 'reg_lambda': 1.1546303286100679}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  46%|████▌     | 23/50 [07:04<05:22, 11.93s/it]

[I 2026-03-15 21:58:13,097] Trial 22 pruned. 


Best trial: 3. Best value: 0.944569:  48%|████▊     | 24/50 [07:11<04:29, 10.36s/it]

[I 2026-03-15 21:58:19,810] Trial 23 pruned. 


Best trial: 3. Best value: 0.944569:  50%|█████     | 25/50 [07:36<06:08, 14.72s/it]

[I 2026-03-15 21:58:44,692] Trial 24 finished with value: 0.9409080369511895 and parameters: {'learning_rate': 0.06067581514633306, 'max_depth': 12, 'min_child_weight': 8.528035486444772, 'subsample': 0.7582772888004757, 'colsample_bytree': 0.8710329345531955, 'gamma': 1.6510256661618357, 'reg_alpha': 0.29434344824032505, 'reg_lambda': 0.7286433243187915}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  52%|█████▏    | 26/50 [07:42<04:51, 12.14s/it]

[I 2026-03-15 21:58:50,805] Trial 25 pruned. 


Best trial: 3. Best value: 0.944569:  54%|█████▍    | 27/50 [07:49<04:00, 10.48s/it]

[I 2026-03-15 21:58:57,403] Trial 26 pruned. 


Best trial: 3. Best value: 0.944569:  56%|█████▌    | 28/50 [08:15<05:35, 15.26s/it]

[I 2026-03-15 21:59:23,821] Trial 27 finished with value: 0.9415327591213957 and parameters: {'learning_rate': 0.016559922651142176, 'max_depth': 11, 'min_child_weight': 5.744322051095581, 'subsample': 0.7821250790817458, 'colsample_bytree': 0.6950268704851201, 'gamma': 1.345285686761528, 'reg_alpha': 0.00035868039648027114, 'reg_lambda': 0.11636251782079449}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  58%|█████▊    | 29/50 [08:23<04:31, 12.93s/it]

[I 2026-03-15 21:59:31,306] Trial 28 pruned. 


Best trial: 3. Best value: 0.944569:  60%|██████    | 30/50 [08:29<03:42, 11.12s/it]

[I 2026-03-15 21:59:38,211] Trial 29 pruned. 


Best trial: 3. Best value: 0.944569:  62%|██████▏   | 31/50 [08:57<05:06, 16.13s/it]

[I 2026-03-15 22:00:06,011] Trial 30 finished with value: 0.9428472226666093 and parameters: {'learning_rate': 0.03193874426784791, 'max_depth': 11, 'min_child_weight': 19.50453868941307, 'subsample': 0.7373112093515864, 'colsample_bytree': 0.5905440903488085, 'gamma': 0.05423570337473582, 'reg_alpha': 0.00041437560986184985, 'reg_lambda': 0.14911868845250553}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  64%|██████▍   | 32/50 [09:23<05:40, 18.93s/it]

[I 2026-03-15 22:00:31,480] Trial 31 finished with value: 0.9425043380318764 and parameters: {'learning_rate': 0.033199341860024774, 'max_depth': 11, 'min_child_weight': 18.561562347971478, 'subsample': 0.7355855622961766, 'colsample_bytree': 0.5491179439812433, 'gamma': 0.15244209977913714, 'reg_alpha': 0.0003618166049411172, 'reg_lambda': 0.1479627667898202}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  66%|██████▌   | 33/50 [09:31<04:26, 15.67s/it]

[I 2026-03-15 22:00:39,536] Trial 32 pruned. 


Best trial: 3. Best value: 0.944569:  68%|██████▊   | 34/50 [09:39<03:33, 13.34s/it]

[I 2026-03-15 22:00:47,433] Trial 33 pruned. 


Best trial: 3. Best value: 0.944569:  70%|███████   | 35/50 [10:02<04:04, 16.30s/it]

[I 2026-03-15 22:01:10,659] Trial 34 finished with value: 0.9421682539585173 and parameters: {'learning_rate': 0.0467171236549694, 'max_depth': 9, 'min_child_weight': 21.65702733985818, 'subsample': 0.6909222527768831, 'colsample_bytree': 0.5870966497243291, 'gamma': 0.006843761949726551, 'reg_alpha': 0.00011583844775594826, 'reg_lambda': 0.3219040481017351}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  72%|███████▏  | 36/50 [10:27<04:23, 18.80s/it]

[I 2026-03-15 22:01:35,272] Trial 35 finished with value: 0.9420766126724863 and parameters: {'learning_rate': 0.030246583471953324, 'max_depth': 12, 'min_child_weight': 17.046806312950352, 'subsample': 0.7451194630983582, 'colsample_bytree': 0.5080976720599699, 'gamma': 0.518397609626527, 'reg_alpha': 0.00388914720534117, 'reg_lambda': 0.48783670281493696}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  74%|███████▍  | 37/50 [10:33<03:17, 15.21s/it]

[I 2026-03-15 22:01:42,123] Trial 36 pruned. 


Best trial: 3. Best value: 0.944569:  76%|███████▌  | 38/50 [11:03<03:54, 19.57s/it]

[I 2026-03-15 22:02:11,861] Trial 37 finished with value: 0.9417346888211416 and parameters: {'learning_rate': 0.03797256875551933, 'max_depth': 6, 'min_child_weight': 9.802136176448046, 'subsample': 0.8290973248460497, 'colsample_bytree': 0.5484115546855831, 'gamma': 0.43273474024172287, 'reg_alpha': 0.00041581342291295564, 'reg_lambda': 0.156541752963358}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  78%|███████▊  | 39/50 [11:09<02:49, 15.45s/it]

[I 2026-03-15 22:02:17,698] Trial 38 pruned. 


Best trial: 3. Best value: 0.944569:  80%|████████  | 40/50 [11:16<02:08, 12.87s/it]

[I 2026-03-15 22:02:24,562] Trial 39 pruned. 


Best trial: 3. Best value: 0.944569:  82%|████████▏ | 41/50 [11:22<01:39, 11.00s/it]

[I 2026-03-15 22:02:31,193] Trial 40 pruned. 


Best trial: 3. Best value: 0.944569:  84%|████████▍ | 42/50 [11:45<01:56, 14.61s/it]

[I 2026-03-15 22:02:54,218] Trial 41 finished with value: 0.9425207093824373 and parameters: {'learning_rate': 0.04256555422556949, 'max_depth': 9, 'min_child_weight': 19.47694306430741, 'subsample': 0.6910738313563669, 'colsample_bytree': 0.5824209858518204, 'gamma': 0.21338100494085663, 'reg_alpha': 0.00011810563711500742, 'reg_lambda': 0.3344407507733813}. Best is trial 3 with value: 0.9445689904457429.


Best trial: 3. Best value: 0.944569:  86%|████████▌ | 43/50 [11:53<01:27, 12.49s/it]

[I 2026-03-15 22:03:01,767] Trial 42 pruned. 


Best trial: 3. Best value: 0.944569:  88%|████████▊ | 44/50 [12:00<01:05, 10.85s/it]

[I 2026-03-15 22:03:08,786] Trial 43 pruned. 


Best trial: 3. Best value: 0.944569:  90%|█████████ | 45/50 [12:07<00:48,  9.66s/it]

[I 2026-03-15 22:03:15,671] Trial 44 pruned. 


Best trial: 3. Best value: 0.944569:  92%|█████████▏| 46/50 [12:14<00:35,  8.80s/it]

[I 2026-03-15 22:03:22,472] Trial 45 pruned. 


Best trial: 3. Best value: 0.944569:  94%|█████████▍| 47/50 [12:20<00:24,  8.17s/it]

[I 2026-03-15 22:03:29,183] Trial 46 pruned. 


Best trial: 3. Best value: 0.944569:  96%|█████████▌| 48/50 [12:37<00:21, 10.65s/it]

[I 2026-03-15 22:03:45,616] Trial 47 pruned. 


Best trial: 3. Best value: 0.944569:  98%|█████████▊| 49/50 [12:44<00:09,  9.53s/it]

[I 2026-03-15 22:03:52,532] Trial 48 pruned. 


Best trial: 3. Best value: 0.944569: 100%|██████████| 50/50 [12:50<00:00, 15.40s/it]

[I 2026-03-15 22:03:58,325] Trial 49 pruned. 
Best ranker params (ndcg@5 = 0.944569):
{
  "learning_rate": 0.03438586247938296,
  "max_depth": 11,
  "min_child_weight": 2.5081156860452323,
  "subsample": 0.8056937753654446,
  "colsample_bytree": 0.7962072844310213,
  "gamma": 0.23225206359998862,
  "reg_alpha": 0.1090747583515769,
  "reg_lambda": 0.24682044079890128
}

Top 10 trials:


,trial_label,mean_best_iteration,mean_ndcg@5,mean_recall@5,mean_map@5,mean_roc_auc,learning_rate,max_depth,min_child_weight,subsample,colsample_bytree,gamma,reg_alpha,reg_lambda
0,optuna_003,222.333333,0.944569,0.847160,0.921254,0.856795,0.034386,11,2.508116,0.805694,0.796207,0.232252,0.109075,0.246820
1,optuna_030,152.666667,0.942847,0.846576,0.918799,0.852922,0.031939,11,19.504539,0.737311,0.590544,0.054236,0.000414,0.149119
2,optuna_041,94.000000,0.942521,0.847229,0.918290,0.848702,0.042566,9,19.476943,0.691074,0.582421,0.213381,0.000118,0.334441
3,optuna_031,103.333333,0.942504,0.847099,0.917919,0.853313,0.033199,11,18.561562,0.735586,0.549118,0.152442,0.000362,0.147963
4,optuna_017,136.333333,0.942239,0.847345,0.917991,0.852008,0.097135,6,5.143425,0.766326,0.750541,0.136095,0.016082,0.431527
5,optuna_034,91.666667,0.942168,0.846229,0.917669,0.848116,0.046717,9,21.657027,0.690922,0.587097,0.006844,0.000116,0.321904
6,optuna_035,107.333333,0.942077,0.846903,0.917661,0.854815,0.030247,12,17.046806,0.745119,0.508098,0.518398,0.003889,0.487837
7,optuna_037,268.000000,0.941735,0.847128,0.917167,0.845951,0.037973,6,9.802136,0.829097,0.548412,0.432735,0.000416,0.156542
8,optuna_027,138.000000,0.941533,0.846105,0.917168,0.856942,0.016560,11,5.744322,0.782125,0.695027,1.345286,0.000359,0.116363
9,optuna_011,98.000000,0.941140,0.846382,0.916506,0.859349,0.058685,10,2.827167,0.778458,0.899136,1.793931,0.000218,2.899640


In [22]:
# ── Stage 2: Train on train → val, then retrain on train+val → test ───────────

stage2_val_model = fit_ranker_with_validation(
    row_train_df, row_val_df, pruned_row_feature_cols, pruned_row_fill_values_train, stage2_best_params
)
stage2_val_best_iter = getattr(stage2_val_model, 'best_iteration', None)
stage2_val_best_rounds = int(stage2_val_best_iter + 1) if stage2_val_best_iter is not None else TUNING_N_ESTIMATORS

# Best trial's mean iteration from CV
best_trial_row = stage2_trial_df.iloc[0]
stage2_final_n_estimators = int(np.ceil(
    max(best_trial_row['mean_best_iteration'], stage2_val_best_rounds) * FINAL_N_ESTIMATOR_BUFFER
))

# Retrain on train+val
combined_train_val_df = pd.concat([row_train_df, row_val_df], ignore_index=True)
stage2_final_model = fit_final_ranker(
    combined_train_val_df, pruned_row_feature_cols, pruned_row_fill_values_final,
    stage2_best_params, n_estimators=stage2_final_n_estimators
)

# Score validation and test
stage2_val_scored = score_ranker(stage2_val_model, row_val_df, pruned_row_feature_cols, pruned_row_fill_values_train, 'xgb_ranker_val')
stage2_test_scored = score_ranker(stage2_final_model, row_test_df, pruned_row_feature_cols, pruned_row_fill_values_final, 'xgb_ranker_final')

stage2_val_results, stage2_val_track_metrics = evaluate_ranked_candidates(stage2_val_scored, k=TOP_K)
stage2_test_results, stage2_test_track_metrics = evaluate_ranked_candidates(stage2_test_scored, k=TOP_K)

print(f'Stage 2 final_n_estimators: {stage2_final_n_estimators}')
print()

# Full model comparison: naive baseline → logistic regression → XGBRanker
model_comparison = pd.DataFrame([
    {'split': 'test', 'model': 'naive_popularity',
     f'recall@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'map@{TOP_K}']},
    {'split': 'test', 'model': 'logistic_regression',
     f'recall@{TOP_K}': lr_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': lr_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': lr_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': lr_test_results['ranking_all_tracks'][f'map@{TOP_K}']},
    {'split': 'validation', 'model': 'xgb_ranker',
     f'recall@{TOP_K}': stage2_val_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': stage2_val_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': stage2_val_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': stage2_val_results['ranking_all_tracks'][f'map@{TOP_K}']},
    {'split': 'test', 'model': 'xgb_ranker',
     f'recall@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
     f'ndcg@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
     f'hit_rate@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
     f'map@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'map@{TOP_K}']},
])
print('Full model comparison (naive → logistic regression → XGBRanker):')
display(model_comparison)

Stage 2 final_n_estimators: 711

Full model comparison (naive → logistic regression → XGBRanker):


,split,model,recall@5,ndcg@5,hit_rate@5,map@5
0,test,naive_popularity,0.071285,0.105515,0.241654,0.078229
1,test,logistic_regression,0.581135,0.593875,0.809666,0.526138
2,validation,xgb_ranker,0.647261,0.686967,0.862643,0.628033
3,test,xgb_ranker,0.669267,0.726995,0.873941,0.676781


In [ ]:
# ── Linear Regression Baseline for Timing ─────────────────────────────────────

from sklearn.linear_model import LinearRegression

# Train on positive rows only (tracks that actually spread)
X_train_time_lr = make_feature_matrix(positive_train_rows, pruned_row_feature_cols, pruned_row_fill_values_train)
y_train_time_lr = positive_train_rows['days_to_entry'].astype(float).to_numpy()

X_val_time_lr = make_feature_matrix(positive_val_rows, pruned_row_feature_cols, pruned_row_fill_values_train)
y_val_time_lr = positive_val_rows['days_to_entry'].astype(float).to_numpy()

X_test_time_lr = make_feature_matrix(positive_test_rows, pruned_row_feature_cols, pruned_row_fill_values_final)
y_test_time_lr = positive_test_rows['days_to_entry'].astype(float).to_numpy()

# Standardize features (fit on train only)
lr_time_scaler = StandardScaler()
X_train_time_lr_scaled = lr_time_scaler.fit_transform(X_train_time_lr)
X_val_time_lr_scaled = lr_time_scaler.transform(X_val_time_lr)
X_test_time_lr_scaled = lr_time_scaler.transform(X_test_time_lr)

# Train linear regression
lr_time_model = LinearRegression(n_jobs=-1)
lr_time_model.fit(X_train_time_lr_scaled, y_train_time_lr)
print(f'Linear Regression (timing) fitted: {lr_time_model.n_features_in_} features, R² on train = {lr_time_model.score(X_train_time_lr_scaled, y_train_time_lr):.4f}')

# Predict and clip to [1, 60] (valid range for days_to_entry)
lr_time_pred_val = np.clip(lr_time_model.predict(X_val_time_lr_scaled), 1.0, 60.0)
lr_time_pred_test = np.clip(lr_time_model.predict(X_test_time_lr_scaled), 1.0, 60.0)

# Evaluate
lr_time_val_metrics = regression_metrics(y_val_time_lr, lr_time_pred_val)
lr_time_test_metrics = regression_metrics(y_test_time_lr, lr_time_pred_test)

lr_time_summary_df = pd.DataFrame([
    {'split': 'validation', 'model': 'linear_regression', **lr_time_val_metrics},
    {'split': 'test', 'model': 'linear_regression', **lr_time_test_metrics},
])
print()
print('Linear Regression timing baseline:')
display(lr_time_summary_df)

# ── Coefficient analysis ─────────────────────────────────────────────────────

lr_time_coef_df = pd.DataFrame({
    'feature': pruned_row_feature_cols,
    'coefficient': lr_time_model.coef_,
    'abs_coefficient': np.abs(lr_time_model.coef_),
    'category': [feature_category(f) for f in pruned_row_feature_cols],
}).sort_values('abs_coefficient', ascending=False).reset_index(drop=True)

print()
print('Top 20 most influential features (Linear Regression timing, standardized coefficients):')
print('Positive = increases days to entry (slower spread)')
print('Negative = decreases days to entry (faster spread)')
print()
display(lr_time_coef_df.head(20)[['feature', 'coefficient', 'category']])

# Category-level summary
lr_time_category_summary = (
    lr_time_coef_df.groupby('category')['abs_coefficient']
    .agg(['mean', 'sum', 'count'])
    .sort_values('sum', ascending=False)
    .rename(columns={'mean': 'avg_abs_coef', 'sum': 'total_abs_coef', 'count': 'n_features'})
)
print()
print('Feature importance by category (Linear Regression timing):')
display(lr_time_category_summary)

In [26]:
# ── Optuna objective for Stage 3 regressor with temporal CV ───────────────────

# Build temporal folds on positive training rows
positive_time_folds = make_temporal_folds(positive_train_rows, time_blocks=TIME_BLOCKS)

stage3_trial_records = []


def regressor_objective(trial):
    target_transform = trial.suggest_categorical('target_transform', ['identity', 'log1p', 'sqrt'])
    params = {
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_float('min_child_weight', 1.0, 50.0, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.1, 20.0, log=True),
    }

    fold_maes = []
    for fold_idx, fold in enumerate(positive_time_folds):
        fold_train = positive_train_rows[positive_train_rows['track_id'].isin(fold['train_track_ids'])].copy()
        fold_val = positive_train_rows[positive_train_rows['track_id'].isin(fold['val_track_ids'])].copy()
        if fold_val.empty:
            continue
        fold_fill = fold_train[pruned_row_feature_cols].median(numeric_only=True)

        X_train = make_feature_matrix(fold_train, pruned_row_feature_cols, fold_fill)
        y_train = transform_target(fold_train['days_to_entry'].astype(float), target_transform)
        X_val = make_feature_matrix(fold_val, pruned_row_feature_cols, fold_fill)

        model = make_regressor(params, n_estimators=800, early_stopping_rounds=30)
        y_val_transformed = transform_target(fold_val['days_to_entry'].astype(float), target_transform)
        model.fit(X_train, y_train, eval_set=[(X_val, y_val_transformed)], verbose=False)

        raw_preds = model.predict(X_val)
        preds = np.clip(inverse_transform_target(raw_preds, target_transform), 1.0, 60.0)
        mae = float(mean_absolute_error(fold_val['days_to_entry'].astype(float), preds))
        fold_maes.append(mae)

        trial.report(np.mean(fold_maes), fold_idx)
        if trial.should_prune():
            raise optuna.TrialPruned()

    mean_mae = float(np.mean(fold_maes))
    stage3_trial_records.append({
        'trial_label': f'optuna_{trial.number:03d}',
        'mean_mae': mean_mae,
        'target_transform': target_transform,
        **params,
    })
    return mean_mae


stage3_study = optuna.create_study(
    direction='minimize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_startup_trials=OPTUNA_N_STARTUP_TRIALS, n_warmup_steps=0),
)
stage3_study.optimize(regressor_objective, n_trials=REGRESSOR_N_TRIALS, show_progress_bar=True)

stage3_best_params = {k: v for k, v in stage3_study.best_params.items() if k != 'target_transform'}
stage3_target_transform = stage3_study.best_params['target_transform']
stage3_trial_df = pd.DataFrame(stage3_trial_records).sort_values('mean_mae', ascending=True).reset_index(drop=True)

print(f'Best regressor params (MAE = {stage3_study.best_value:.4f}, transform = {stage3_target_transform}):')
print(json.dumps(stage3_best_params, indent=2))
print()
display(stage3_trial_df.head(10))

[I 2026-03-15 22:09:50,914] A new study created in memory with name: no-name-cbcd42ee-8cf4-48c5-a927-b4bddd37879b
Best trial: 0. Best value: 8.69154:   3%|▎         | 1/30 [00:03<01:48,  3.75s/it]

[I 2026-03-15 22:09:54,663] Trial 0 finished with value: 8.6915410134245 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.050591436432963696, 'max_depth': 4, 'min_child_weight': 1.8408992080552518, 'subsample': 0.6232334448672797, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.10129197956845731, 'reg_lambda': 4.258888210290081}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:   7%|▋         | 2/30 [00:09<02:24,  5.18s/it]

[I 2026-03-15 22:10:00,834] Trial 1 finished with value: 8.803229024517458 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.01777174904859463, 'max_depth': 4, 'min_child_weight': 2.0492680115417348, 'subsample': 0.721696897183815, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.01444525102276306, 'reg_lambda': 0.46787192650162013}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  10%|█         | 3/30 [00:14<02:17,  5.08s/it]

[I 2026-03-15 22:10:05,810] Trial 2 finished with value: 10.006050628584449 and parameters: {'target_transform': 'identity', 'learning_rate': 0.026969628335735185, 'max_depth': 6, 'min_child_weight': 21.576967455896824, 'subsample': 0.6798695128633439, 'colsample_bytree': 0.7571172192068059, 'reg_alpha': 0.0916374180877878, 'reg_lambda': 0.12790390175145838}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  13%|█▎        | 4/30 [00:16<01:38,  3.80s/it]

[I 2026-03-15 22:10:07,651] Trial 3 finished with value: 10.144142632551143 and parameters: {'target_transform': 'identity', 'learning_rate': 0.13060986669773664, 'max_depth': 10, 'min_child_weight': 23.628864184236406, 'subsample': 0.7218455076693483, 'colsample_bytree': 0.5488360570031919, 'reg_alpha': 0.2637333993381525, 'reg_lambda': 1.0299214204601976}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  17%|█▋        | 5/30 [00:18<01:20,  3.24s/it]

[I 2026-03-15 22:10:09,889] Trial 4 finished with value: 8.703232464921646 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.1173393765991262, 'max_depth': 5, 'min_child_weight': 13.353819088790582, 'subsample': 0.7246844304357644, 'colsample_bytree': 0.7600340105889054, 'reg_alpha': 0.05414413211338523, 'reg_lambda': 0.2662904839829044}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  20%|██        | 6/30 [00:20<01:05,  2.74s/it]

[I 2026-03-15 22:10:11,651] Trial 5 finished with value: 9.86079482909382 and parameters: {'target_transform': 'identity', 'learning_rate': 0.11282325501221332, 'max_depth': 7, 'min_child_weight': 36.83296438423419, 'subsample': 0.6353970008207678, 'colsample_bytree': 0.5979914312095727, 'reg_alpha': 0.00016832027985721928, 'reg_lambda': 0.5605248221933015}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  23%|██▎       | 7/30 [00:26<01:25,  3.71s/it]

[I 2026-03-15 22:10:17,368] Trial 6 finished with value: 8.892914035865344 and parameters: {'target_transform': 'sqrt', 'learning_rate': 0.026276920623647244, 'max_depth': 5, 'min_child_weight': 8.356499023325524, 'subsample': 0.6563696899899051, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 0.0002359137306347715, 'reg_lambda': 18.65762858779245}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  27%|██▋       | 8/30 [00:28<01:09,  3.14s/it]

[I 2026-03-15 22:10:19,285] Trial 7 finished with value: 10.074435905964805 and parameters: {'target_transform': 'identity', 'learning_rate': 0.09100328259258599, 'max_depth': 8, 'min_child_weight': 17.320535358459537, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.5370223258670452, 'reg_alpha': 0.006199100007802264, 'reg_lambda': 0.18476435128841198}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  30%|███       | 9/30 [00:33<01:21,  3.87s/it]

[I 2026-03-15 22:10:24,757] Trial 8 finished with value: 10.075372543409257 and parameters: {'target_transform': 'identity', 'learning_rate': 0.011878194167382767, 'max_depth': 5, 'min_child_weight': 3.568426123255423, 'subsample': 0.8918424713352257, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 2.7293781650374735, 'reg_lambda': 1.2206206339370174}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  33%|███▎      | 10/30 [00:38<01:23,  4.15s/it]

[I 2026-03-15 22:10:29,550] Trial 9 finished with value: 8.898880459004651 and parameters: {'target_transform': 'sqrt', 'learning_rate': 0.04572073526670409, 'max_depth': 9, 'min_child_weight': 6.901506581791921, 'subsample': 0.8090931317527976, 'colsample_bytree': 0.7137705091792748, 'reg_alpha': 0.0001339971723117974, 'reg_lambda': 0.17711747399775965}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  37%|███▋      | 11/30 [00:41<01:11,  3.78s/it]

[I 2026-03-15 22:10:32,475] Trial 10 finished with value: 8.786777188998727 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.05874214516124276, 'max_depth': 3, 'min_child_weight': 1.0727948694969764, 'subsample': 0.6058108720480717, 'colsample_bytree': 0.9538323976412588, 'reg_alpha': 6.2929420103194795, 'reg_lambda': 8.446825354521486}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  40%|████      | 12/30 [00:43<00:58,  3.23s/it]

[I 2026-03-15 22:10:34,464] Trial 11 finished with value: 8.826310563629065 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.07386391228000022, 'max_depth': 3, 'min_child_weight': 8.453033914356988, 'subsample': 0.7849378345686582, 'colsample_bytree': 0.9959564504559631, 'reg_alpha': 0.33631322583582063, 'reg_lambda': 4.282478495081483}. Best is trial 0 with value: 8.6915410134245.


Best trial: 0. Best value: 8.69154:  43%|████▎     | 13/30 [00:45<00:48,  2.87s/it]

[I 2026-03-15 22:10:36,493] Trial 12 finished with value: 8.697241117448401 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.14936920996220396, 'max_depth': 5, 'min_child_weight': 4.042246295527444, 'subsample': 0.796052593872792, 'colsample_bytree': 0.8681667029564858, 'reg_alpha': 0.003601283278983452, 'reg_lambda': 3.175696711539786}. Best is trial 0 with value: 8.6915410134245.


Best trial: 13. Best value: 8.63396:  47%|████▋     | 14/30 [00:50<00:58,  3.64s/it]

[I 2026-03-15 22:10:41,901] Trial 13 finished with value: 8.633960331442665 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.036124323050328325, 'max_depth': 6, 'min_child_weight': 2.5114272486958527, 'subsample': 0.9869745933861575, 'colsample_bytree': 0.8827776453146763, 'reg_alpha': 0.0022138518597612815, 'reg_lambda': 3.1424466929967694}. Best is trial 13 with value: 8.633960331442665.


Best trial: 14. Best value: 8.5997:  50%|█████     | 15/30 [01:01<01:23,  5.56s/it] 

[I 2026-03-15 22:10:51,916] Trial 14 finished with value: 8.599699248209852 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.033650193834597726, 'max_depth': 7, 'min_child_weight': 1.1302750553844805, 'subsample': 0.9903553734978908, 'colsample_bytree': 0.9119745033366308, 'reg_alpha': 0.000843914981900611, 'reg_lambda': 2.99702316212815}. Best is trial 14 with value: 8.599699248209852.


Best trial: 14. Best value: 8.5997:  53%|█████▎    | 16/30 [01:08<01:27,  6.23s/it]

[I 2026-03-15 22:10:59,701] Trial 15 finished with value: 8.621552407869535 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.0315543665879116, 'max_depth': 7, 'min_child_weight': 1.3141397346528068, 'subsample': 0.9764563410891148, 'colsample_bytree': 0.8403191087718804, 'reg_alpha': 0.000924901806550109, 'reg_lambda': 2.521360005074865}. Best is trial 14 with value: 8.599699248209852.


Best trial: 14. Best value: 8.5997:  57%|█████▋    | 17/30 [01:17<01:29,  6.85s/it]

[I 2026-03-15 22:11:08,001] Trial 16 finished with value: 8.644544862971781 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.030689736409675112, 'max_depth': 8, 'min_child_weight': 1.3163058658694544, 'subsample': 0.9997045969047512, 'colsample_bytree': 0.8211810280697476, 'reg_alpha': 0.0006612141905238356, 'reg_lambda': 1.6608395666576143}. Best is trial 14 with value: 8.599699248209852.


Best trial: 14. Best value: 8.5997:  60%|██████    | 18/30 [01:21<01:11,  5.98s/it]

[I 2026-03-15 22:11:11,951] Trial 17 pruned. 


Best trial: 14. Best value: 8.5997:  63%|██████▎   | 19/30 [01:32<01:23,  7.61s/it]

[I 2026-03-15 22:11:23,352] Trial 18 finished with value: 8.617945142181881 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.022335207472459217, 'max_depth': 8, 'min_child_weight': 4.7439342287037825, 'subsample': 0.8571389722362222, 'colsample_bytree': 0.8268548079220718, 'reg_alpha': 0.0007205197374139146, 'reg_lambda': 6.803327132503825}. Best is trial 14 with value: 8.599699248209852.


Best trial: 19. Best value: 8.57151:  67%|██████▋   | 20/30 [01:50<01:47, 10.75s/it]

[I 2026-03-15 22:11:41,421] Trial 19 finished with value: 8.571508027273623 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.020444234311898752, 'max_depth': 9, 'min_child_weight': 4.036726679140651, 'subsample': 0.8562048371962279, 'colsample_bytree': 0.9905216967889842, 'reg_alpha': 0.009636960348402055, 'reg_lambda': 7.8231030219623}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  70%|███████   | 21/30 [02:07<01:52, 12.50s/it]

[I 2026-03-15 22:11:58,016] Trial 20 pruned. 


Best trial: 19. Best value: 8.57151:  73%|███████▎  | 22/30 [02:24<01:52, 14.09s/it]

[I 2026-03-15 22:12:15,811] Trial 21 finished with value: 8.59854276498698 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.020050442294010665, 'max_depth': 9, 'min_child_weight': 5.6132640257019135, 'subsample': 0.851429629506362, 'colsample_bytree': 0.9279244127229767, 'reg_alpha': 0.0021222162528655056, 'reg_lambda': 8.338665658740803}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  77%|███████▋  | 23/30 [02:42<01:45, 15.08s/it]

[I 2026-03-15 22:12:33,187] Trial 22 finished with value: 8.590269219398921 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.015646393970779684, 'max_depth': 9, 'min_child_weight': 5.625996804604362, 'subsample': 0.9357207087053551, 'colsample_bytree': 0.9385120515287854, 'reg_alpha': 0.007071074872301877, 'reg_lambda': 5.998179274026896}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  80%|████████  | 24/30 [03:02<01:38, 16.49s/it]

[I 2026-03-15 22:12:52,979] Trial 23 finished with value: 8.607244545063972 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.015059774263620353, 'max_depth': 9, 'min_child_weight': 6.124994394139478, 'subsample': 0.8674227334885064, 'colsample_bytree': 0.9648535209868637, 'reg_alpha': 0.015047289736509512, 'reg_lambda': 6.438088128810542}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  83%|████████▎ | 25/30 [03:21<01:27, 17.47s/it]

[I 2026-03-15 22:13:12,716] Trial 24 finished with value: 8.6011926202822 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.014680748324949106, 'max_depth': 9, 'min_child_weight': 11.364589673595601, 'subsample': 0.9402567450018868, 'colsample_bytree': 0.9487009911257916, 'reg_alpha': 0.005788860130506341, 'reg_lambda': 12.69133623379119}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  87%|████████▋ | 26/30 [03:40<01:11, 17.87s/it]

[I 2026-03-15 22:13:31,535] Trial 25 finished with value: 8.596525935742061 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.0216141579734014, 'max_depth': 10, 'min_child_weight': 5.216833662506072, 'subsample': 0.7647345218450798, 'colsample_bytree': 0.9739258557249856, 'reg_alpha': 0.0022193347470337473, 'reg_lambda': 12.129433741403787}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  90%|█████████ | 27/30 [04:11<01:05, 21.69s/it]

[I 2026-03-15 22:14:02,118] Trial 26 finished with value: 8.590901250173546 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.013716946681684189, 'max_depth': 10, 'min_child_weight': 3.3419565156171163, 'subsample': 0.7828228539550262, 'colsample_bytree': 0.996430095054221, 'reg_alpha': 0.0307086821346853, 'reg_lambda': 19.908466057392488}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  93%|█████████▎| 28/30 [04:39<00:47, 23.70s/it]

[I 2026-03-15 22:14:30,509] Trial 27 finished with value: 8.620859996035735 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.01294395905818316, 'max_depth': 10, 'min_child_weight': 3.293051043568524, 'subsample': 0.9474957137587757, 'colsample_bytree': 0.9950508948649073, 'reg_alpha': 0.022234405720742718, 'reg_lambda': 18.313829316276266}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151:  97%|█████████▋| 29/30 [05:04<00:23, 23.91s/it]

[I 2026-03-15 22:14:54,918] Trial 28 finished with value: 8.63881496812428 and parameters: {'target_transform': 'log1p', 'learning_rate': 0.010007100652565513, 'max_depth': 9, 'min_child_weight': 1.8512725423219625, 'subsample': 0.8923999425709396, 'colsample_bytree': 0.85938506794257, 'reg_alpha': 0.38703941407610903, 'reg_lambda': 5.9437733252925495}. Best is trial 19 with value: 8.571508027273623.


Best trial: 19. Best value: 8.57151: 100%|██████████| 30/30 [05:07<00:00, 10.26s/it]

[I 2026-03-15 22:14:58,664] Trial 29 pruned. 
Best regressor params (MAE = 8.5715, transform = log1p):
{
  "learning_rate": 0.020444234311898752,
  "max_depth": 9,
  "min_child_weight": 4.036726679140651,
  "subsample": 0.8562048371962279,
  "colsample_bytree": 0.9905216967889842,
  "reg_alpha": 0.009636960348402055,
  "reg_lambda": 7.8231030219623
}



,trial_label,mean_mae,target_transform,learning_rate,max_depth,min_child_weight,subsample,colsample_bytree,reg_alpha,reg_lambda
0,optuna_019,8.571508,log1p,0.020444,9,4.036727,0.856205,0.990522,0.009637,7.823103
1,optuna_022,8.590269,log1p,0.015646,9,5.625997,0.935721,0.938512,0.007071,5.998179
2,optuna_026,8.590901,log1p,0.013717,10,3.341957,0.782823,0.996430,0.030709,19.908466
3,optuna_025,8.596526,log1p,0.021614,10,5.216834,0.764735,0.973926,0.002219,12.129434
4,optuna_021,8.598543,log1p,0.020050,9,5.613264,0.851430,0.927924,0.002122,8.338666
5,optuna_014,8.599699,log1p,0.033650,7,1.130275,0.990355,0.911975,0.000844,2.997023
6,optuna_024,8.601193,log1p,0.014681,9,11.364590,0.940257,0.948701,0.005789,12.691336
7,optuna_023,8.607245,log1p,0.015060,9,6.124994,0.867423,0.964854,0.015047,6.438088
8,optuna_018,8.617945,log1p,0.022335,8,4.743934,0.857139,0.826855,0.000721,6.803327
9,optuna_027,8.620860,log1p,0.012944,10,3.293051,0.947496,0.995051,0.022234,18.313829


In [27]:
# ── Train Stage 3 regressor: train → val, then retrain on train+val ──────────

stage3_val_model = fit_regressor_with_validation(
    positive_train_rows, positive_val_rows,
    pruned_row_feature_cols, pruned_row_fill_values_train,
    stage3_best_params, target_transform=stage3_target_transform,
)
stage3_val_best_iter = getattr(stage3_val_model, 'best_iteration', None)
stage3_val_best_rounds = int(stage3_val_best_iter + 1) if stage3_val_best_iter is not None else 800

# Val metrics
stage3_val_scored = score_regressor(
    stage3_val_model, positive_val_rows, pruned_row_feature_cols, pruned_row_fill_values_train,
    target_transform=stage3_target_transform,
)
stage3_val_metrics = regression_metrics(
    stage3_val_scored['days_to_entry'].astype(float).to_numpy(),
    stage3_val_scored['predicted_days_to_entry'].astype(float).to_numpy(),
)

# Retrain on train+val
combined_positive = pd.concat([positive_train_rows, positive_val_rows], ignore_index=True)
stage3_final_n_estimators = int(np.ceil(stage3_val_best_rounds * FINAL_N_ESTIMATOR_BUFFER))
stage3_final_model = fit_final_regressor(
    combined_positive, pruned_row_feature_cols, pruned_row_fill_values_final,
    stage3_best_params, n_estimators=stage3_final_n_estimators,
    target_transform=stage3_target_transform,
)

# Test metrics
stage3_test_scored = score_regressor(
    stage3_final_model, positive_test_rows, pruned_row_feature_cols, pruned_row_fill_values_final,
    target_transform=stage3_target_transform,
)
stage3_test_metrics = regression_metrics(
    stage3_test_scored['days_to_entry'].astype(float).to_numpy(),
    stage3_test_scored['predicted_days_to_entry'].astype(float).to_numpy(),
)

# Score ALL rows for pipeline integration
stage3_val_all_scored = score_regressor(stage3_val_model, row_val_df, pruned_row_feature_cols, pruned_row_fill_values_train, target_transform=stage3_target_transform)
stage3_test_all_scored = score_regressor(stage3_final_model, row_test_df, pruned_row_feature_cols, pruned_row_fill_values_final, target_transform=stage3_target_transform)

stage3_summary_df = pd.DataFrame([
    {'split': 'validation', 'target_transform': stage3_target_transform, **stage3_val_metrics},
    {'split': 'test', 'target_transform': stage3_target_transform, **stage3_test_metrics},
])
print('Stage 3 regression summary:')
display(stage3_summary_df)

Stage 3 regression summary:


,split,target_transform,mae,rmse,median_ae,pct_within_3_days,pct_within_7_days
0,validation,log1p,8.381966,14.210641,3.483331,0.460217,0.669930
1,test,log1p,7.764729,13.467457,3.208202,0.484422,0.693354


In [23]:
# ── Optuna objective for Stage 1 classifier with temporal CV ──────────────────

# Build track-level temporal folds from the same time blocks
track_time_folds = make_temporal_folds(track_train_df, time_blocks=TIME_BLOCKS)

stage1_trial_records = []


def classifier_objective(trial):
    params = {
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'min_child_weight': trial.suggest_float('min_child_weight', 1.0, 50.0, log=True),
        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 0.5, 10.0),
        'max_delta_step': trial.suggest_int('max_delta_step', 0, 5),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.1, 20.0, log=True),
    }

    fold_aps = []
    for fold_idx, fold in enumerate(track_time_folds):
        fold_train = track_train_df[track_train_df['track_id'].isin(fold['train_track_ids'])].copy()
        fold_val = track_train_df[track_train_df['track_id'].isin(fold['val_track_ids'])].copy()
        fold_fill = fold_train[pruned_track_feature_cols].median(numeric_only=True)

        X_train = make_feature_matrix(fold_train, pruned_track_feature_cols, fold_fill)
        y_train = fold_train['will_spread'].astype(int)
        X_val = make_feature_matrix(fold_val, pruned_track_feature_cols, fold_fill)
        y_val = fold_val['will_spread'].astype(int)

        model = xgb.XGBClassifier(
            objective='binary:logistic', eval_metric='aucpr', tree_method='hist',
            n_estimators=500, early_stopping_rounds=30,
            random_state=RANDOM_STATE, n_jobs=-1, **params,
        )
        model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)
        val_probs = model.predict_proba(X_val)[:, 1]
        ap = float(average_precision_score(y_val, val_probs))
        fold_aps.append(ap)

        trial.report(np.mean(fold_aps), fold_idx)
        if trial.should_prune():
            raise optuna.TrialPruned()

    mean_ap = float(np.mean(fold_aps))
    stage1_trial_records.append({
        'trial_label': f'optuna_{trial.number:03d}',
        'mean_average_precision': mean_ap,
        **params,
    })
    return mean_ap


stage1_study = optuna.create_study(
    direction='maximize',
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
    pruner=optuna.pruners.MedianPruner(n_startup_trials=OPTUNA_N_STARTUP_TRIALS, n_warmup_steps=0),
)
stage1_study.optimize(classifier_objective, n_trials=CLASSIFIER_N_TRIALS, show_progress_bar=True)

stage1_best_params = stage1_study.best_params
stage1_trial_df = pd.DataFrame(stage1_trial_records).sort_values('mean_average_precision', ascending=False).reset_index(drop=True)

print(f'Best classifier params (avg precision = {stage1_study.best_value:.6f}):')
print(json.dumps(stage1_best_params, indent=2))
print()
display(stage1_trial_df.head(10))

[I 2026-03-15 22:06:53,517] A new study created in memory with name: no-name-d62fbf9b-6306-4957-a201-980819e77ef9
Best trial: 0. Best value: 0.81493:   3%|▎         | 1/30 [00:08<04:09,  8.59s/it]

[I 2026-03-15 22:07:02,109] Trial 0 finished with value: 0.8149301274034176 and parameters: {'learning_rate': 0.02757359293934948, 'max_depth': 8, 'min_child_weight': 17.524101118128137, 'scale_pos_weight': 6.187255599871848, 'max_delta_step': 0, 'subsample': 0.662397808134481, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.142302175774105, 'reg_lambda': 2.416482602989751}. Best is trial 0 with value: 0.8149301274034176.


Best trial: 0. Best value: 0.81493:   7%|▋         | 2/30 [00:13<03:01,  6.48s/it]

[I 2026-03-15 22:07:07,103] Trial 1 finished with value: 0.8016614017691595 and parameters: {'learning_rate': 0.06803900745073703, 'max_depth': 3, 'min_child_weight': 44.447541666908116, 'scale_pos_weight': 8.408205087604006, 'max_delta_step': 1, 'subsample': 0.6727299868828402, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 0.003320559103751959, 'reg_lambda': 1.6124278458562613}. Best is trial 0 with value: 0.8149301274034176.


Best trial: 0. Best value: 0.81493:  10%|█         | 3/30 [00:19<02:46,  6.18s/it]

[I 2026-03-15 22:07:12,929] Trial 2 finished with value: 0.8091740407453328 and parameters: {'learning_rate': 0.032211189352044464, 'max_depth': 4, 'min_child_weight': 10.952662748632553, 'scale_pos_weight': 1.8251916761943974, 'max_delta_step': 1, 'subsample': 0.7465447373174766, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 0.8431013932082458, 'reg_lambda': 0.2880416977880551}. Best is trial 0 with value: 0.8149301274034176.


Best trial: 0. Best value: 0.81493:  13%|█▎        | 4/30 [00:27<02:55,  6.76s/it]

[I 2026-03-15 22:07:20,583] Trial 3 finished with value: 0.812831820864716 and parameters: {'learning_rate': 0.04025192252635066, 'max_depth': 6, 'min_child_weight': 1.199272452295516, 'scale_pos_weight': 6.271676093063665, 'max_delta_step': 1, 'subsample': 0.6260206371941118, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 6.732248920775334, 'reg_lambda': 7.24680451825845}. Best is trial 0 with value: 0.8149301274034176.


Best trial: 0. Best value: 0.81493:  17%|█▋        | 5/30 [00:31<02:24,  5.78s/it]

[I 2026-03-15 22:07:24,611] Trial 4 finished with value: 0.7664760574963543 and parameters: {'learning_rate': 0.022816739880816207, 'max_depth': 3, 'min_child_weight': 14.537555576161921, 'scale_pos_weight': 4.681448690526213, 'max_delta_step': 0, 'subsample': 0.798070764044508, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 3.520481045526035, 'reg_lambda': 0.3939675937754722}. Best is trial 0 with value: 0.8149301274034176.


Best trial: 0. Best value: 0.81493:  20%|██        | 6/30 [00:35<02:11,  5.46s/it]

[I 2026-03-15 22:07:29,472] Trial 5 finished with value: 0.808943620849217 and parameters: {'learning_rate': 0.06014321882783979, 'max_depth': 4, 'min_child_weight': 7.648565112369945, 'scale_pos_weight': 5.693747653761156, 'max_delta_step': 1, 'subsample': 0.9878338511058234, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 4.983043837494905, 'reg_lambda': 11.455777613940603}. Best is trial 0 with value: 0.8149301274034176.


Best trial: 6. Best value: 0.816014:  23%|██▎       | 7/30 [00:43<02:22,  6.19s/it]

[I 2026-03-15 22:07:37,168] Trial 6 finished with value: 0.8160140676570121 and parameters: {'learning_rate': 0.05048762470240496, 'max_depth': 8, 'min_child_weight': 1.4136637008121844, 'scale_pos_weight': 2.3618371929818793, 'max_delta_step': 0, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 0.002273762810253686, 'reg_lambda': 8.071418522169692}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  27%|██▋       | 8/30 [00:49<02:14,  6.10s/it]

[I 2026-03-15 22:07:43,058] Trial 7 finished with value: 0.8083847992733455 and parameters: {'learning_rate': 0.026276920623647244, 'max_depth': 4, 'min_child_weight': 8.356499023325524, 'scale_pos_weight': 1.8387801372602453, 'max_delta_step': 4, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 0.7264803074826723, 'reg_lambda': 0.28658321062461245}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  30%|███       | 9/30 [00:59<02:30,  7.18s/it]

[I 2026-03-15 22:07:52,604] Trial 8 finished with value: 0.8022712693120448 and parameters: {'learning_rate': 0.010150665434429315, 'max_depth': 7, 'min_child_weight': 15.882886211970037, 'scale_pos_weight': 7.425568096389379, 'max_delta_step': 4, 'subsample': 0.6296178606936361, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 0.00037961668958008145, 'reg_lambda': 9.683377710407786}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  33%|███▎      | 10/30 [01:04<02:15,  6.78s/it]

[I 2026-03-15 22:07:58,487] Trial 9 finished with value: 0.8124595609589284 and parameters: {'learning_rate': 0.054082340576877566, 'max_depth': 4, 'min_child_weight': 1.2822825454807552, 'scale_pos_weight': 3.454332056298791, 'max_delta_step': 1, 'subsample': 0.8918424713352257, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 2.7293781650374735, 'reg_lambda': 1.2206206339370174}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  37%|███▋      | 11/30 [01:08<01:52,  5.91s/it]

[I 2026-03-15 22:08:02,421] Trial 10 finished with value: 0.8128882589717948 and parameters: {'learning_rate': 0.13224010746937992, 'max_depth': 8, 'min_child_weight': 2.66932249811483, 'scale_pos_weight': 0.6706378183407864, 'max_delta_step': 3, 'subsample': 0.7447070264153981, 'colsample_bytree': 0.6338413443561857, 'reg_alpha': 0.009167785859319854, 'reg_lambda': 3.461107795152951}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  40%|████      | 12/30 [01:11<01:29,  5.00s/it]

[I 2026-03-15 22:08:05,337] Trial 11 pruned. 


Best trial: 6. Best value: 0.816014:  43%|████▎     | 13/30 [01:16<01:23,  4.89s/it]

[I 2026-03-15 22:08:09,968] Trial 12 pruned. 


Best trial: 6. Best value: 0.816014:  47%|████▋     | 14/30 [01:28<01:53,  7.10s/it]

[I 2026-03-15 22:08:22,194] Trial 13 finished with value: 0.8141621873731176 and parameters: {'learning_rate': 0.016937912903521486, 'max_depth': 7, 'min_child_weight': 3.2040193664623935, 'scale_pos_weight': 2.791991780447046, 'max_delta_step': 0, 'subsample': 0.6978753170579768, 'colsample_bytree': 0.6130206056184311, 'reg_alpha': 0.06358498687791131, 'reg_lambda': 0.9165463556364796}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  50%|█████     | 15/30 [01:36<01:49,  7.28s/it]

[I 2026-03-15 22:08:29,887] Trial 14 finished with value: 0.8140136472375429 and parameters: {'learning_rate': 0.04093129124863014, 'max_depth': 8, 'min_child_weight': 23.598258493546073, 'scale_pos_weight': 6.571617017248747, 'max_delta_step': 5, 'subsample': 0.8124496121405842, 'colsample_bytree': 0.70760330818165, 'reg_alpha': 0.0009214539672161129, 'reg_lambda': 3.582161725966495}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  53%|█████▎    | 16/30 [01:39<01:26,  6.15s/it]

[I 2026-03-15 22:08:33,396] Trial 15 pruned. 


Best trial: 6. Best value: 0.816014:  57%|█████▋    | 17/30 [01:42<01:07,  5.21s/it]

[I 2026-03-15 22:08:36,432] Trial 16 pruned. 


Best trial: 6. Best value: 0.816014:  60%|██████    | 18/30 [01:56<01:32,  7.72s/it]

[I 2026-03-15 22:08:50,003] Trial 17 finished with value: 0.8144413457637271 and parameters: {'learning_rate': 0.02014194153332884, 'max_depth': 8, 'min_child_weight': 5.353391646932023, 'scale_pos_weight': 9.107797409399364, 'max_delta_step': 2, 'subsample': 0.8605160480249973, 'colsample_bytree': 0.6601698676289585, 'reg_alpha': 0.0019210324227487544, 'reg_lambda': 2.272706509045642}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  63%|██████▎   | 19/30 [01:58<01:06,  6.09s/it]

[I 2026-03-15 22:08:52,281] Trial 18 pruned. 


Best trial: 6. Best value: 0.816014:  67%|██████▋   | 20/30 [02:01<00:51,  5.17s/it]

[I 2026-03-15 22:08:55,318] Trial 19 pruned. 


Best trial: 6. Best value: 0.816014:  70%|███████   | 21/30 [02:03<00:36,  4.03s/it]

[I 2026-03-15 22:08:56,703] Trial 20 pruned. 


Best trial: 6. Best value: 0.816014:  73%|███████▎  | 22/30 [02:06<00:31,  3.93s/it]

[I 2026-03-15 22:09:00,390] Trial 21 pruned. 


Best trial: 6. Best value: 0.816014:  77%|███████▋  | 23/30 [02:15<00:37,  5.39s/it]

[I 2026-03-15 22:09:09,196] Trial 22 finished with value: 0.8133202609486231 and parameters: {'learning_rate': 0.029818488653664137, 'max_depth': 7, 'min_child_weight': 5.49398237498314, 'scale_pos_weight': 8.998375523464485, 'max_delta_step': 2, 'subsample': 0.7728253580935763, 'colsample_bytree': 0.6955045676779492, 'reg_alpha': 0.000908610048866444, 'reg_lambda': 2.147215090381314}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 6. Best value: 0.816014:  80%|████████  | 24/30 [02:18<00:28,  4.75s/it]

[I 2026-03-15 22:09:12,447] Trial 23 pruned. 


Best trial: 6. Best value: 0.816014:  83%|████████▎ | 25/30 [02:28<00:30,  6.19s/it]

[I 2026-03-15 22:09:21,988] Trial 24 finished with value: 0.814053152655085 and parameters: {'learning_rate': 0.022663193438098233, 'max_depth': 7, 'min_child_weight': 10.320721857370257, 'scale_pos_weight': 8.667171213081765, 'max_delta_step': 3, 'subsample': 0.7083156983188331, 'colsample_bytree': 0.738882778929416, 'reg_alpha': 0.00016410543887282215, 'reg_lambda': 2.448723257342465}. Best is trial 6 with value: 0.8160140676570121.


Best trial: 25. Best value: 0.816053:  87%|████████▋ | 26/30 [02:36<00:26,  6.74s/it]

[I 2026-03-15 22:09:30,002] Trial 25 finished with value: 0.8160527390981244 and parameters: {'learning_rate': 0.04334437267484656, 'max_depth': 8, 'min_child_weight': 5.918214065158989, 'scale_pos_weight': 5.55474209172425, 'max_delta_step': 5, 'subsample': 0.9316754076154603, 'colsample_bytree': 0.5609573015198609, 'reg_alpha': 0.028459272955920437, 'reg_lambda': 0.5637592794071168}. Best is trial 25 with value: 0.8160527390981244.


Best trial: 25. Best value: 0.816053:  90%|█████████ | 27/30 [02:38<00:15,  5.20s/it]

[I 2026-03-15 22:09:31,619] Trial 26 pruned. 


Best trial: 25. Best value: 0.816053:  93%|█████████▎| 28/30 [02:45<00:11,  5.87s/it]

[I 2026-03-15 22:09:39,051] Trial 27 finished with value: 0.8153960343144829 and parameters: {'learning_rate': 0.03687410178968451, 'max_depth': 7, 'min_child_weight': 21.2879436295935, 'scale_pos_weight': 5.302972130567276, 'max_delta_step': 4, 'subsample': 0.9400959612838816, 'colsample_bytree': 0.5794502693025919, 'reg_alpha': 0.41966721942104407, 'reg_lambda': 0.12331540197585228}. Best is trial 25 with value: 0.8160527390981244.


Best trial: 25. Best value: 0.816053:  97%|█████████▋| 29/30 [02:47<00:04,  4.69s/it]

[I 2026-03-15 22:09:40,994] Trial 28 pruned. 


Best trial: 25. Best value: 0.816053: 100%|██████████| 30/30 [02:54<00:00,  5.80s/it]

[I 2026-03-15 22:09:47,529] Trial 29 finished with value: 0.8129221905367666 and parameters: {'learning_rate': 0.032802243775014533, 'max_depth': 6, 'min_child_weight': 23.287377051967493, 'scale_pos_weight': 3.8975976190774944, 'max_delta_step': 5, 'subsample': 0.9170820441984977, 'colsample_bytree': 0.5763506667838815, 'reg_alpha': 0.8257766249961005, 'reg_lambda': 0.1732529388415077}. Best is trial 25 with value: 0.8160527390981244.
Best classifier params (avg precision = 0.816053):
{
  "learning_rate": 0.04334437267484656,
  "max_depth": 8,
  "min_child_weight": 5.918214065158989,
  "scale_pos_weight": 5.55474209172425,
  "max_delta_step": 5,
  "subsample": 0.9316754076154603,
  "colsample_bytree": 0.5609573015198609,
  "reg_alpha": 0.028459272955920437,
  "reg_lambda": 0.5637592794071168
}



,trial_label,mean_average_precision,learning_rate,max_depth,min_child_weight,scale_pos_weight,max_delta_step,subsample,colsample_bytree,reg_alpha,reg_lambda
0,optuna_025,0.816053,0.043344,8,5.918214,5.554742,5,0.931675,0.560957,0.028459,0.563759
1,optuna_006,0.816014,0.050488,8,1.413664,2.361837,0,0.730132,0.694339,0.002274,8.071419
2,optuna_027,0.815396,0.036874,7,21.287944,5.302972,4,0.940096,0.579450,0.419667,0.123315
3,optuna_000,0.814930,0.027574,8,17.524101,6.187256,0,0.662398,0.529042,2.142302,2.416483
4,optuna_017,0.814441,0.020142,8,5.353392,9.107797,2,0.860516,0.660170,0.001921,2.272707
5,optuna_013,0.814162,0.016938,7,3.204019,2.791992,0,0.697875,0.613021,0.063585,0.916546
6,optuna_024,0.814053,0.022663,7,10.320722,8.667171,3,0.708316,0.738883,0.000164,2.448723
7,optuna_014,0.814014,0.040931,8,23.598258,6.571617,5,0.812450,0.707603,0.000921,3.582162
8,optuna_022,0.813320,0.029818,7,5.493982,8.998376,2,0.772825,0.695505,0.000909,2.147215
9,optuna_029,0.812922,0.032802,6,23.287377,3.897598,5,0.917082,0.576351,0.825777,0.173253


In [24]:
# ── Train Stage 1 classifier + isotonic calibration ──────────────────────────

X_track_train = make_feature_matrix(track_train_df, pruned_track_feature_cols, pruned_track_fill_values)
X_track_val = make_feature_matrix(track_val_df, pruned_track_feature_cols, pruned_track_fill_values)
X_track_test = make_feature_matrix(track_test_df, pruned_track_feature_cols, pruned_track_fill_values)
y_track_train = track_train_df['will_spread'].astype(int)
y_track_val = track_val_df['will_spread'].astype(int)
y_track_test = track_test_df['will_spread'].astype(int)

stage1_model = xgb.XGBClassifier(
    objective='binary:logistic', eval_metric='aucpr', tree_method='hist',
    n_estimators=500, early_stopping_rounds=30,
    random_state=RANDOM_STATE, n_jobs=-1, **stage1_best_params,
)
stage1_model.fit(X_track_train, y_track_train, eval_set=[(X_track_val, y_track_val)], verbose=False)

# Raw (uncalibrated) scores
stage1_raw_val_scores = stage1_model.predict_proba(X_track_val)[:, 1]
stage1_raw_test_scores = stage1_model.predict_proba(X_track_test)[:, 1]

raw_val_brier = float(brier_score_loss(y_track_val, np.clip(stage1_raw_val_scores, 1e-6, 1 - 1e-6)))
print(f'Raw (uncalibrated) Brier score on val: {raw_val_brier:.4f}')

# Isotonic calibration: fit on validation raw scores → true labels
stage1_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')
stage1_calibrator.fit(stage1_raw_val_scores, y_track_val)

stage1_cal_val_scores = stage1_calibrator.predict(stage1_raw_val_scores)
stage1_cal_test_scores = stage1_calibrator.predict(stage1_raw_test_scores)

cal_val_brier = float(brier_score_loss(y_track_val, np.clip(stage1_cal_val_scores, 1e-6, 1 - 1e-6)))
cal_test_brier = float(brier_score_loss(y_track_test, np.clip(stage1_cal_test_scores, 1e-6, 1 - 1e-6)))
print(f'Calibrated Brier score on val: {cal_val_brier:.4f}')
print(f'Calibrated Brier score on test: {cal_test_brier:.4f}')

# Build scored DataFrames with calibrated probabilities
stage1_val_scored = track_val_df[['track_id', 'observation_time', 'origin_country_count_at_obs', 'candidate_count', 'will_spread']].copy()
stage1_val_scored['score'] = stage1_cal_val_scores
stage1_val_scored['raw_score'] = stage1_raw_val_scores

stage1_test_scored = track_test_df[['track_id', 'observation_time', 'origin_country_count_at_obs', 'candidate_count', 'will_spread']].copy()
stage1_test_scored['score'] = stage1_cal_test_scores
stage1_test_scored['raw_score'] = stage1_raw_test_scores

# Select thresholds on calibrated scores
stage1_threshold_summary, stage1_threshold_map, stage1_threshold_sweep = build_business_threshold_summary(
    y_track_val, stage1_cal_val_scores, BUSINESS_PRECISION_FLOORS, beta=2.0,
)

stage1_threshold_rows = []
for floor in BUSINESS_PRECISION_FLOORS:
    threshold = float(stage1_threshold_map[float(floor)])
    reason = stage1_threshold_summary.loc[stage1_threshold_summary['precision_floor'] == float(floor), 'selection_reason'].iloc[0]
    stage1_threshold_rows.append({
        'split': 'validation', 'precision_floor': float(floor), 'threshold': threshold,
        'selection_reason': reason,
        **binary_summary(y_track_val, stage1_cal_val_scores, threshold=threshold),
    })
    stage1_threshold_rows.append({
        'split': 'test', 'precision_floor': float(floor), 'threshold': threshold,
        'selection_reason': reason + ' (chosen on validation)',
        **binary_summary(y_track_test, stage1_cal_test_scores, threshold=threshold),
    })
stage1_threshold_df = pd.DataFrame(stage1_threshold_rows)

# Apply decisions
for floor, threshold in stage1_threshold_map.items():
    col = f'spread_decision_floor_{float(floor):.2f}'.replace('.', '_')
    stage1_val_scored[col] = (stage1_val_scored['score'] >= float(threshold)).astype(int)
    stage1_test_scored[col] = (stage1_test_scored['score'] >= float(threshold)).astype(int)

print()
print('Stage 1 threshold summary (calibrated):')
display(stage1_threshold_df)

# Show raw vs calibrated comparison
raw_val_summary = binary_summary(y_track_val, stage1_raw_val_scores, threshold=0.5)
cal_val_summary = binary_summary(y_track_val, stage1_cal_val_scores, threshold=float(stage1_threshold_map[PRIMARY_PRECISION_FLOOR]))
calibration_comparison = pd.DataFrame([
    {'version': 'raw (threshold=0.5)', 'brier_score': raw_val_brier,
     'precision': raw_val_summary['precision'], 'recall': raw_val_summary['recall']},
    {'version': f'calibrated (threshold={stage1_threshold_map[PRIMARY_PRECISION_FLOOR]:.3f})',
     'brier_score': cal_val_brier,
     'precision': cal_val_summary['precision'], 'recall': cal_val_summary['recall']},
])
print()
print('Raw vs calibrated (validation):')
display(calibration_comparison)

Raw (uncalibrated) Brier score on val: 0.8541
Calibrated Brier score on val: 0.0622
Calibrated Brier score on test: 0.0668

Stage 1 threshold summary (calibrated):


,split,precision_floor,threshold,selection_reason,roc_auc,average_precision,log_loss,brier_score,precision,recall,f1,f2.0,positive_rate,predicted_positive_rate,flagged_per_1000_tracks
0,validation,0.20,0.076923,highest recall with precision >= 0.20,0.830155,0.336747,0.219978,0.062209,0.204583,0.759506,0.322340,0.492389,0.081367,0.302073,302.072859
1,test,0.20,0.076923,highest recall with precision >= 0.20 (chosen ...,0.811580,0.288855,0.236351,0.066753,0.202095,0.720977,0.315698,0.476363,0.083462,0.297750,297.750239
2,validation,0.25,0.090909,highest recall with precision >= 0.25,0.830155,0.336747,0.219978,0.062209,0.251912,0.673004,0.366602,0.504381,0.081367,0.217380,217.379534
3,test,0.25,0.090909,highest recall with precision >= 0.25 (chosen ...,0.811580,0.288855,0.236351,0.066753,0.240927,0.621824,0.347294,0.472441,0.083462,0.215411,215.411486



Raw vs calibrated (validation):


,version,brier_score,precision,recall
0,raw (threshold=0.5),0.854127,0.081383,1.000000
1,calibrated (threshold=0.077),0.062209,0.204583,0.759506


## 6. Results — How Does Each Model Perform?

With all models trained, we now compare their performance. We organize results by task: ranking first, then timing, then the gate ablation.

### 6a. Country Ranking Results

**Full comparison table:**

| Metric | Naive Baseline | Logistic Regression | XGBRanker | LR → XGBRanker Improvement |
|--------|---------------|--------------------|-----------|--------------------|
| recall@5 | 0.071 | 0.581 | **0.669** | +15.2% |
| ndcg@5 | 0.106 | 0.594 | **0.727** | +22.4% |
| hit_rate@5 | 0.242 | 0.810 | **0.874** | +7.9% |

**What the numbers mean:**
- **recall@5 = 0.669** means the model correctly identifies 2 out of 3 future chart countries in its top-5 predictions — directly measuring whether Spotify would have targeted the right markets.
- **ndcg@5 = 0.727** shows that relevant countries are ranked *higher* in the list, not just present somewhere. The 22.4% improvement over logistic regression confirms that the listwise ranking objective places the most important markets first.
- **hit_rate@5 = 0.874** means 87.4% of all tracks have at least one correct country in their top-5 — the model is broadly reliable.
- **vs naive popularity baseline:** The 9.4× recall improvement (0.669 vs 0.071) demonstrates strong predictive value beyond simply guessing the most popular countries.

**Logistic Regression coefficient highlights:**
- `artist_prior_unique_regions` (+0.852): Artists with a global track record have the highest spread probability — identifies *established global artists* as the safest bets.
- `same_language_flag` (+0.733): Shared language is the second strongest positive signal, confirming cultural proximity drives spread.
- `target_continent_europe` (−0.647): European markets are harder to enter on average, reflecting linguistic/cultural fragmentation.
- `artist_prior_success_in_target` (+0.609): Existing fan base in a country significantly increases repeat charting probability.
- `cultural_dist_min` (−0.174): Higher cultural distance decreases spread probability, confirming music flows along cultural corridors.

**XGBRanker feature importance:** Origin-target relationship features dominate (total gain = 239.5), followed by current chart footprint (146.1), target country priors (33.2), and artist history (25.9). Both models agree that cultural and geographic proximity are the primary drivers of cross-border diffusion.

**Gap interpretation:** The 15.2% recall improvement from LR to XGBRanker quantifies the value of **non-linear feature interactions**. For example, "high cultural distance BUT the artist already has fans in the target country" may override the cultural barrier — something a linear model cannot capture. The gap is large enough to clearly justify the added model complexity.

**Bootstrap 95% CIs (XGBRanker test set, 1000 samples):** recall@5 ∈ [0.652, 0.687], ndcg@5 ∈ [0.712, 0.742] — confirming statistically robust results.

### 6b. Timing Prediction Results

**Comparison table (test set, positive rows only):**

| Metric | Linear Regression | XGBRegressor | Improvement |
|--------|------------------|-------------|-------------|
| MAE (days) | *see output above* | **7.76** | *computed from outputs* |
| % within 3 days | *see output above* | **48.4%** | *computed from outputs* |
| % within 7 days | *see output above* | **69.3%** | *computed from outputs* |

> **Note:** Linear Regression results are populated from the training output above. The actual comparison values depend on the LR timing model's performance on this specific data split.

**Linear Regression coefficient highlights:**
- Positive coefficients (increase days to entry = slower spread): features indicating cultural/geographic distance or unfamiliar markets
- Negative coefficients (decrease days to entry = faster spread): features indicating cultural proximity, shared language, prior artist presence

**XGBRegressor details:**
- Best target transform: `log1p` (selected by Optuna over identity and sqrt) — appropriate because chart entry timing is right-skewed with most entries in the first 1–2 weeks
- 48.4% of predictions within 3 days — nearly half are operationally precise for campaign timing
- 69.3% within 7 days — over two-thirds fall within a one-week planning window

**Gap interpretation:** The difference between Linear Regression and XGBRegressor MAE quantifies the value of non-linear timing modeling. Non-linear interactions (e.g., "culturally close AND artist has prior presence" → very fast entry) cannot be captured by additive linear terms.

In [25]:
# ── Ablation: gate vs no gate on test set ─────────────────────────────────────

# No gate = standalone ranker on all tracks
no_gate_results = stage2_test_results
no_gate_recall = no_gate_results['ranking_all_tracks'][f'recall@{TOP_K}']
no_gate_ndcg = no_gate_results['ranking_all_tracks'][f'ndcg@{TOP_K}']
no_gate_hit_rate = no_gate_results['ranking_all_tracks'][f'hit_rate@{TOP_K}']

total_test_tracks = len(stage1_test_scored)
total_test_rows = len(row_test_df)

ablation_rows = [{
    'configuration': 'no_gate (standalone ranker)',
    f'recall@{TOP_K}': no_gate_recall,
    f'ndcg@{TOP_K}': no_gate_ndcg,
    f'hit_rate@{TOP_K}': no_gate_hit_rate,
    'tracks_scored': total_test_tracks,
    'rows_to_rank': total_test_rows,
    'recall_cost_vs_no_gate': 0.0,
}]

# With gate at various precision floors
for floor in BUSINESS_PRECISION_FLOORS:
    threshold = float(stage1_threshold_map[float(floor)])
    flagged = stage1_test_scored['score'] >= threshold
    n_flagged = int(flagged.sum())
    n_rows_gated = n_flagged * 65  # ~65 candidate countries per track

    # Compute gated metrics using the test track metrics from stage 2
    gated_track_ids = set(stage1_test_scored.loc[flagged, 'track_id'].tolist())
    gated_test_metrics = stage2_test_track_metrics[stage2_test_track_metrics['track_id'].isin(gated_track_ids)].copy()
    all_test_metrics = stage2_test_track_metrics.copy()

    positive_mask = all_test_metrics['positives'] > 0
    total_positive_tracks = int(positive_mask.sum())

    gated_positive = gated_test_metrics[gated_test_metrics['positives'] > 0]
    gated_recall = float(gated_positive[f'recall@{TOP_K}'].sum() / max(total_positive_tracks, 1)) if not gated_positive.empty else 0.0
    gated_ndcg = float(gated_positive[f'ndcg@{TOP_K}'].sum() / max(total_positive_tracks, 1)) if not gated_positive.empty else 0.0
    gated_hit_rate = float(gated_positive[f'hit_rate@{TOP_K}'].sum() / max(total_positive_tracks, 1)) if not gated_positive.empty else 0.0

    ablation_rows.append({
        'configuration': f'gate (pfloor={floor:.2f}, threshold={threshold:.3f})',
        f'recall@{TOP_K}': gated_recall,
        f'ndcg@{TOP_K}': gated_ndcg,
        f'hit_rate@{TOP_K}': gated_hit_rate,
        'tracks_scored': n_flagged,
        'rows_to_rank': n_rows_gated,
        'recall_cost_vs_no_gate': no_gate_recall - gated_recall,
    })

ablation_df = pd.DataFrame(ablation_rows)
print('Stage 1 Ablation: Gate vs No Gate (test set)')
display(ablation_df)
print()
print(f'Without gate: {total_test_tracks:,} tracks x ~65 countries = {total_test_rows:,} rows to rank')
print(f'Business tradeoff: The gate reduces inference cost but misses some spreading tracks.')
print(f'Recommendation: Use the gate only if inference cost is a hard constraint.')

Stage 1 Ablation: Gate vs No Gate (test set)


,configuration,recall@5,ndcg@5,hit_rate@5,tracks_scored,rows_to_rank,recall_cost_vs_no_gate
0,no_gate (standalone ranker),0.669267,0.726995,0.873941,24047,1535867,0.000000
1,"gate (pfloor=0.20, threshold=0.077)",0.459480,0.519990,0.631290,7160,465400,0.209788
2,"gate (pfloor=0.25, threshold=0.091)",0.384560,0.444830,0.545092,5180,336700,0.284708



Without gate: 24,047 tracks x ~65 countries = 1,535,867 rows to rank
Business tradeoff: The gate reduces inference cost but misses some spreading tracks.
Recommendation: Use the gate only if inference cost is a hard constraint.


### 6c. Ablation: Gate vs No Gate

| Configuration | recall@5 | Recall cost vs no gate |
|--------------|----------|----------------------|
| No gate (standalone ranker) | **0.669** | — |
| Gate at pfloor=0.20 | 0.459 | −0.210 (−31.4%) |
| Gate at pfloor=0.25 | 0.385 | −0.285 (−42.6%) |

The gate drops recall by 21–43% depending on the threshold. While it reduces inference cost (scoring only flagged tracks instead of all tracks × 65 countries), this recall loss is unacceptable for a recommendation system where **missing a spreading track means missing a market opportunity**.

**Calibration results:** Isotonic calibration dramatically improved the classifier's probability estimates — the Brier score dropped from 0.854 (raw) to 0.062 (calibrated on validation) and 0.067 (calibrated on test). Despite this well-calibrated classifier, the gate still harms recall because the binary spread decision is inherently lossy: some tracks that spread to only 1–2 countries are correctly classified as "not spreading broadly" but their target countries are still missed by the ranker.

**Conclusion:** The gate is not worth the recall cost. Use the standalone ranker for production.

## 7. Model Selection — Which Do We Choose?

### Ranking Task: XGBRanker

The XGBRanker delivers a **15.2% recall improvement** over Logistic Regression (0.669 vs 0.581) and a **9.4× improvement** over the naive popularity baseline. The added complexity of gradient boosting is clearly justified:

- Non-linear feature interactions capture cultural corridors that linear models miss
- The listwise `rank:ndcg` objective directly optimizes what we care about — ordered country lists
- Bootstrap CIs confirm the result is robust (recall@5 ∈ [0.652, 0.687])

**Decision:** XGBRanker as the production ranking model.

### Timing Task: XGBRegressor vs Linear Regression

Both models are evaluated on the same positive test rows. The XGBRegressor achieves MAE = 7.76 days with 48.4% of predictions within 3 days. The Linear Regression baseline provides the comparison point — if the gap is small, the simpler model suffices; if large, the non-linear model earns its complexity.

**Decision:** Select based on the MAE gap observed in the results above. Given the right-skewed nature of days_to_entry and the known non-linear interactions between features, the XGBRegressor is expected to outperform.

### Pre-Filtering Gate: No

The gate costs 21–43% recall depending on threshold — far too high for a recommendation system where missing a spreading track means missing a market opportunity. The standalone ranker processes ~1.5M rows per batch, which is manageable with modern hardware.

### Combined Recommendation

**Standalone XGBRanker** for country prediction + **XGBRegressor** (or Linear Regression if competitive) for timing. No gate. This combination provides:
- Top-5 country predictions with 66.9% recall
- Timing estimates with ~8-day MAE for campaign planning
- Full interpretability through both LR coefficients (direction) and XGB gain importance (magnitude)

In [28]:
# ── End-to-end pipeline evaluation ────────────────────────────────────────────

# Assemble pipeline predictions (val + test)
val_pipeline = add_stage1_to_row_predictions(stage2_val_scored, stage1_val_scored, stage1_threshold_map)
val_pipeline = add_regression_predictions(val_pipeline, stage3_val_all_scored)
val_pipeline = add_predicted_rank(val_pipeline)
val_pipeline = val_pipeline.rename(columns={'score': 'rank_score'})

test_pipeline = add_stage1_to_row_predictions(stage2_test_scored, stage1_test_scored, stage1_threshold_map)
test_pipeline = add_regression_predictions(test_pipeline, stage3_test_all_scored)
test_pipeline = add_predicted_rank(test_pipeline)
test_pipeline = test_pipeline.rename(columns={'score': 'rank_score'})

# Evaluate gated pipeline at each precision floor
pipeline_rows = []
for split_name, pipeline_df in [('validation', val_pipeline), ('test', test_pipeline)]:
    for floor in BUSINESS_PRECISION_FLOORS:
        gate_col = f'spread_decision_floor_{float(floor):.2f}'.replace('.', '_')
        gated_df = pipeline_df.copy().rename(columns={'rank_score': 'score'})
        ranking_summary, _, day_metrics, _ = evaluate_gated_pipeline(gated_df, gate_col=gate_col, k=TOP_K)
        pipeline_rows.append({
            'split': split_name, 'precision_floor': float(floor),
            **ranking_summary,
            **{f'days_{k}': v for k, v in day_metrics.items()},
        })

pipeline_summary_df = pd.DataFrame(pipeline_rows).sort_values(['split', 'precision_floor']).reset_index(drop=True)
print('End-to-end pipeline summary:')
display(pipeline_summary_df)

# ── Bootstrap confidence intervals on test set ───────────────────────────────

rng_boot = np.random.default_rng(RANDOM_STATE)
test_track_ids = stage2_test_track_metrics['track_id'].unique()
positive_test_track_metrics = stage2_test_track_metrics[stage2_test_track_metrics['positives'] > 0].copy()
positive_track_ids = positive_test_track_metrics['track_id'].unique()

n_bootstrap = 1000
n_tracks = len(positive_track_ids)
metrics_indexed = positive_test_track_metrics.set_index('track_id')
recall_vals = metrics_indexed.loc[positive_track_ids, f'recall@{TOP_K}'].values
ndcg_vals = metrics_indexed.loc[positive_track_ids, f'ndcg@{TOP_K}'].values
map_vals = metrics_indexed.loc[positive_track_ids, f'map@{TOP_K}'].values

# Vectorized bootstrap: sample indices, then compute means in one shot
sample_indices = rng_boot.integers(0, n_tracks, size=(n_bootstrap, n_tracks))
boot_recalls = recall_vals[sample_indices].mean(axis=1)
boot_ndcgs = ndcg_vals[sample_indices].mean(axis=1)
boot_maps = map_vals[sample_indices].mean(axis=1)

ci_df = pd.DataFrame([
    {'metric': f'recall@{TOP_K}', 'mean': float(boot_recalls.mean()),
     'ci_lower': float(np.percentile(boot_recalls, 2.5)), 'ci_upper': float(np.percentile(boot_recalls, 97.5))},
    {'metric': f'ndcg@{TOP_K}', 'mean': float(boot_ndcgs.mean()),
     'ci_lower': float(np.percentile(boot_ndcgs, 2.5)), 'ci_upper': float(np.percentile(boot_ndcgs, 97.5))},
    {'metric': f'map@{TOP_K}', 'mean': float(boot_maps.mean()),
     'ci_lower': float(np.percentile(boot_maps, 2.5)), 'ci_upper': float(np.percentile(boot_maps, 97.5))},
])
print()
print(f'Bootstrap 95% CIs on test set ({n_bootstrap} samples, standalone ranker):')
display(ci_df)

# ── Cross-notebook model comparison ──────────────────────────────────────────

comparison_rows = []

# Load prior evaluation summaries
eval_sources = {
    'NB06 Prototype': ROOT / 'artifacts' / 'evaluations' / 'xgboost_prototype' / 'evaluation_summary.json',
    'NB08 Full XGBClassifier': ROOT / 'artifacts' / 'evaluations' / 'xgboost_full' / 'evaluation_summary.json',
    'NB09 XGBRanker': ROOT / 'artifacts' / 'evaluations' / 'xgboost_ranker_temporal_tuned' / 'evaluation_summary.json',
    'NB11 Pipeline': ROOT / 'artifacts' / 'evaluations' / 'xgboost_multitask_pipeline' / 'pipeline_summary.json',
}

for label, path in eval_sources.items():
    if not path.exists():
        continue
    data = json.loads(path.read_text())
    test_data = data.get('test', {})

    if label == 'NB11 Pipeline':
        # Pipeline summary has different structure
        pipeline_rows_data = data.get('pipeline', {}).get('summary_rows', [])
        for row in pipeline_rows_data:
            if row.get('split') == 'test' and row.get('precision_floor') == 0.20:
                comparison_rows.append({
                    'notebook': label,
                    f'recall@{TOP_K}': row.get(f'recall@{TOP_K}'),
                    f'ndcg@{TOP_K}': row.get(f'ndcg@{TOP_K}'),
                    f'hit_rate@{TOP_K}': row.get(f'hit_rate@{TOP_K}'),
                })
                break
    else:
        # Standard evaluation_summary.json
        for model_name, summary in test_data.items():
            if 'naive' in model_name or 'baseline' in model_name:
                continue
            ranking = summary.get('ranking_all_tracks', summary.get('ranking_positive_tracks', {}))
            comparison_rows.append({
                'notebook': label,
                f'recall@{TOP_K}': ranking.get(f'recall@{TOP_K}'),
                f'ndcg@{TOP_K}': ranking.get(f'ndcg@{TOP_K}'),
                f'hit_rate@{TOP_K}': ranking.get(f'hit_rate@{TOP_K}'),
            })
            break

# Add current notebook results
comparison_rows.append({
    'notebook': 'NB12 Final (standalone)',
    f'recall@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
    f'ndcg@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
    f'hit_rate@{TOP_K}': stage2_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
})

# Add naive baseline
comparison_rows.append({
    'notebook': 'Naive popularity',
    f'recall@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'recall@{TOP_K}'],
    f'ndcg@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}'],
    f'hit_rate@{TOP_K}': baseline_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}'],
})

model_comparison_df = pd.DataFrame(comparison_rows)
print()
print('Cross-notebook model comparison (test set):')
display(model_comparison_df)

End-to-end pipeline summary:


,split,precision_floor,tracks,positive_tracks,flagged_tracks,precision@5,recall@5,hit_rate@5,ndcg@5,map@5,days_mae,days_rmse,days_median_ae,days_pct_within_3_days,days_pct_within_7_days,days_evaluated_rows
0,test,0.20,24047,2007,7160,0.024203,0.459480,0.631290,0.519990,0.481642,6.420676,11.623416,2.700573,0.531271,0.767354,2910
1,test,0.25,24047,2007,5180,0.021599,0.384560,0.545092,0.444830,0.410515,6.229354,11.469867,2.634049,0.538698,0.777821,2597
2,validation,0.20,25858,2104,7811,0.024024,0.473318,0.660646,0.519784,0.472360,6.670778,12.289906,2.605770,0.539923,0.759176,3106
3,validation,0.25,25858,2104,5621,0.021858,0.410335,0.583650,0.456967,0.414373,6.593902,12.208114,2.550640,0.543878,0.763977,2826



Bootstrap 95% CIs on test set (1000 samples, standalone ranker):


,metric,mean,ci_lower,ci_upper
0,recall@5,0.669300,0.652168,0.687194
1,ndcg@5,0.727149,0.711564,0.742455
2,map@5,0.676907,0.660455,0.693178



Cross-notebook model comparison (test set):


,notebook,recall@5,ndcg@5,hit_rate@5
0,NB06 Prototype,0.617137,0.653777,0.833525
1,NB08 Full XGBClassifier,0.618141,0.650964,0.836572
2,NB09 XGBRanker,0.669348,0.725118,0.875436
3,NB11 Pipeline,0.500679,0.558399,0.677628
4,NB12 Final (standalone),0.669267,0.726995,0.873941
5,Naive popularity,0.071285,0.105515,0.241654


## 8. Visualizations

Feature importance plots, coefficient charts, calibration curves, and bootstrap distributions for the primary models.

In [29]:
# ── Plots ─────────────────────────────────────────────────────────────────────

# Feature importance (Stage 2 ranker)
booster = stage2_final_model.get_booster()
importance_gain = booster.get_score(importance_type='gain')
importance_weight = booster.get_score(importance_type='weight')

importance_df = pd.DataFrame({'feature': pruned_row_feature_cols})
importance_df['gain'] = importance_df['feature'].map(importance_gain).fillna(0.0)
importance_df['weight'] = importance_df['feature'].map(importance_weight).fillna(0.0)
importance_df['category'] = importance_df['feature'].map(feature_category)
importance_df = importance_df.sort_values(['gain', 'weight'], ascending=[False, False]).reset_index(drop=True)

fig, axes = plt.subplots(3, 2, figsize=(18, 21))

# 1. XGBRanker — Top 20 features by gain
plot_gain = importance_df.head(20).sort_values('gain')
axes[0, 0].barh(plot_gain['feature'], plot_gain['gain'], color='steelblue')
axes[0, 0].set_title('XGBRanker: Top 20 Feature Importance (Gain)')
axes[0, 0].set_xlabel('Gain')

# 2. XGBRanker — Category summary
cat_summary = importance_df.groupby('category')['gain'].sum().sort_values(ascending=True)
axes[0, 1].barh(cat_summary.index, cat_summary.values, color='coral')
axes[0, 1].set_title('XGBRanker: Feature Importance by Category')
axes[0, 1].set_xlabel('Total Gain')

# 3. Logistic Regression — Top 20 features by |coefficient|
lr_top20 = lr_coef_df.head(20).sort_values('abs_coefficient')
colors = ['#2ecc71' if c > 0 else '#e74c3c' for c in lr_top20['coefficient']]
axes[1, 0].barh(lr_top20['feature'], lr_top20['coefficient'], color=colors)
axes[1, 0].set_title('Logistic Regression: Top 20 Features (Standardized Coefficients)')
axes[1, 0].set_xlabel('Coefficient (green = increases spread, red = decreases)')
axes[1, 0].axvline(0, color='black', linewidth=0.5)

# 4. Logistic Regression — Category summary
lr_cat_summary = lr_coef_df.groupby('category')['abs_coefficient'].sum().sort_values(ascending=True)
axes[1, 1].barh(lr_cat_summary.index, lr_cat_summary.values, color='mediumpurple')
axes[1, 1].set_title('Logistic Regression: Feature Importance by Category')
axes[1, 1].set_xlabel('Total |Coefficient|')

# 5. Stage 1 PR curve: raw vs calibrated
raw_precision, raw_recall, _ = precision_recall_curve(y_track_test, stage1_raw_test_scores)
cal_precision, cal_recall, _ = precision_recall_curve(y_track_test, stage1_cal_test_scores)
axes[2, 0].plot(raw_recall, raw_precision, label='Raw', alpha=0.7)
axes[2, 0].plot(cal_recall, cal_precision, label='Calibrated (isotonic)', alpha=0.7)
axes[2, 0].set_xlabel('Recall')
axes[2, 0].set_ylabel('Precision')
axes[2, 0].set_title('Stage 1 Precision-Recall Curve (test)')
axes[2, 0].legend()

# 6. Bootstrap distribution histogram
axes[2, 1].hist(boot_recalls, bins=40, alpha=0.7, label=f'recall@{TOP_K}', color='steelblue')
axes[2, 1].hist(boot_ndcgs, bins=40, alpha=0.7, label=f'ndcg@{TOP_K}', color='coral')
axes[2, 1].axvline(np.percentile(boot_recalls, 2.5), color='steelblue', linestyle='--', alpha=0.5)
axes[2, 1].axvline(np.percentile(boot_recalls, 97.5), color='steelblue', linestyle='--', alpha=0.5)
axes[2, 1].axvline(np.percentile(boot_ndcgs, 2.5), color='coral', linestyle='--', alpha=0.5)
axes[2, 1].axvline(np.percentile(boot_ndcgs, 97.5), color='coral', linestyle='--', alpha=0.5)
axes[2, 1].set_title(f'Bootstrap Distribution (test, n={n_bootstrap})')
axes[2, 1].set_xlabel('Metric Value')
axes[2, 1].legend()

plt.tight_layout()
plt.savefig(EVAL_DIR / 'final_evaluation_plots.png', dpi=150, bbox_inches='tight')
plt.show()
plt.close(fig)

print('XGBRanker category importance summary:')
display(importance_df.groupby('category')[['gain', 'weight']].sum().sort_values('gain', ascending=False))

XGBRanker category importance summary:


/var/folders/bl/m0zs7txj4lg0kmvg2zzypg840000gn/T/ipykernel_64614/3941934307.py:65: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


,gain,weight
category,,
origin_target_relationship,239.508816,12654.0
current_footprint,146.052531,34658.0
target_country_priors,33.221124,39156.0
artist_history,25.873804,18873.0
audio_track_metadata,14.572483,47717.0
temporal,3.048839,6386.0


## 9. Artifact Export

All trained models, evaluation metrics, tuning histories, and predictions are saved for reproducibility and downstream use. Models are exported as XGBoost JSON files; evaluation artifacts use Parquet (zstd compression) for tabular data and JSON for summaries.

In [ ]:
# ── Save models ───────────────────────────────────────────────────────────────

stage2_model_path = MODEL_DIR / 'stage2_country_ranker.json'
stage1_model_path = MODEL_DIR / 'stage1_will_spread_classifier.json'
stage1_calibrator_path = MODEL_DIR / 'stage1_calibrator.pkl'
stage3_model_path = MODEL_DIR / 'stage3_days_to_entry_regressor.json'
training_summary_path = MODEL_DIR / 'training_summary.json'

stage2_final_model.save_model(stage2_model_path)
stage1_model.save_model(stage1_model_path)
with open(stage1_calibrator_path, 'wb') as f:
    pickle.dump(stage1_calibrator, f)
stage3_final_model.save_model(stage3_model_path)

# Save logistic regression baseline (ranking)
lr_model_path = MODEL_DIR / 'baseline_logistic_regression.pkl'
lr_scaler_path = MODEL_DIR / 'baseline_lr_scaler.pkl'
with open(lr_model_path, 'wb') as f:
    pickle.dump(lr_model, f)
with open(lr_scaler_path, 'wb') as f:
    pickle.dump(lr_scaler, f)

# Save linear regression baseline (timing)
lr_time_model_path = MODEL_DIR / 'baseline_linear_regression_timing.pkl'
lr_time_scaler_path = MODEL_DIR / 'baseline_lr_time_scaler.pkl'
with open(lr_time_model_path, 'wb') as f:
    pickle.dump(lr_time_model, f)
with open(lr_time_scaler_path, 'wb') as f:
    pickle.dump(lr_time_scaler, f)

# ── Build training summary ───────────────────────────────────────────────────

training_summary = {
    'config': {
        'ranker_n_trials': RANKER_N_TRIALS,
        'classifier_n_trials': CLASSIFIER_N_TRIALS,
        'regressor_n_trials': REGRESSOR_N_TRIALS,
        'time_blocks': TIME_BLOCKS,
        'top_k': TOP_K,
        'primary_precision_floor': PRIMARY_PRECISION_FLOOR,
    },
    'feature_pruning': {
        'row_features_original': len(row_feature_cols),
        'row_features_pruned': len(pruned_row_feature_cols),
        'row_dropped': zero_gain_row,
        'track_features_original': len(track_feature_cols),
        'track_features_pruned': len(pruned_track_feature_cols),
        'track_dropped': zero_gain_track,
    },
    'stage2_ranker': {
        'best_params': stage2_best_params,
        'best_cv_ndcg': float(stage2_study.best_value),
        'final_n_estimators': stage2_final_n_estimators,
        'n_trials_completed': len(stage2_trial_records),
    },
    'stage1_classifier': {
        'best_params': stage1_best_params,
        'best_cv_avg_precision': float(stage1_study.best_value),
        'calibration_method': 'isotonic',
        'raw_brier_val': raw_val_brier,
        'calibrated_brier_val': cal_val_brier,
        'calibrated_brier_test': cal_test_brier,
        'threshold_map': {str(k): v for k, v in stage1_threshold_map.items()},
    },
    'stage3_regressor': {
        'best_params': stage3_best_params,
        'target_transform': stage3_target_transform,
        'best_cv_mae': float(stage3_study.best_value),
        'final_n_estimators': stage3_final_n_estimators,
    },
    'baseline_logistic_regression': {
        'n_features': int(lr_model.n_features_in_),
        'n_iterations': int(lr_model.n_iter_[0]),
        'test_recall': float(lr_test_results['ranking_all_tracks'][f'recall@{TOP_K}']),
        'test_ndcg': float(lr_test_results['ranking_all_tracks'][f'ndcg@{TOP_K}']),
        'test_hit_rate': float(lr_test_results['ranking_all_tracks'][f'hit_rate@{TOP_K}']),
    },
    'baseline_linear_regression_timing': {
        'n_features': int(lr_time_model.n_features_in_),
        'test_mae': float(lr_time_test_metrics['mae']),
        'test_pct_within_3_days': float(lr_time_test_metrics['pct_within_3_days']),
        'test_pct_within_7_days': float(lr_time_test_metrics['pct_within_7_days']),
    },
    'data': {
        'row_train_rows': int(len(row_train_df)),
        'row_val_rows': int(len(row_val_df)),
        'row_test_rows': int(len(row_test_df)),
        'track_train_tracks': int(len(track_train_df)),
        'track_val_tracks': int(len(track_val_df)),
        'track_test_tracks': int(len(track_test_df)),
        'positive_train_rows': int(len(positive_train_rows)),
        'positive_val_rows': int(len(positive_val_rows)),
        'positive_test_rows': int(len(positive_test_rows)),
    },
    'pruned_row_feature_cols': pruned_row_feature_cols,
    'pruned_track_feature_cols': pruned_track_feature_cols,
    'fill_values_train': {col: float(pruned_row_fill_values_train[col]) for col in pruned_row_feature_cols},
    'fill_values_final': {col: float(pruned_row_fill_values_final[col]) for col in pruned_row_feature_cols},
}

with open(training_summary_path, 'w', encoding='utf-8') as f:
    json.dump(training_summary, f, indent=2)

# ── Build pipeline summary ───────────────────────────────────────────────────

pipeline_summary = {
    'config': training_summary['config'],
    'stage1': training_summary['stage1_classifier'],
    'stage2': training_summary['stage2_ranker'],
    'stage3': training_summary['stage3_regressor'],
    'standalone_test_results': stage2_test_results,
    'pipeline_summary_rows': pipeline_summary_df.to_dict(orient='records'),
    'ablation': ablation_df.to_dict(orient='records'),
    'bootstrap_ci': ci_df.to_dict(orient='records'),
    'model_comparison': model_comparison_df.to_dict(orient='records'),
}

pipeline_summary_path = EVAL_DIR / 'pipeline_summary.json'
with open(pipeline_summary_path, 'w', encoding='utf-8') as f:
    json.dump(pipeline_summary, f, indent=2)

# ── Save evaluation parquets ─────────────────────────────────────────────────

parquet_exports = {
    'stage2_tuning_trials': stage2_trial_df,
    'stage2_tuning_folds': stage2_fold_df,
    'stage1_tuning_trials': stage1_trial_df,
    'stage3_tuning_trials': stage3_trial_df,
    'feature_importance': importance_df,
    'lr_coefficients': lr_coef_df,
    'lr_timing_coefficients': lr_time_coef_df,
    'lr_timing_regression_summary': lr_time_summary_df,
    'stage1_threshold_summary': stage1_threshold_df,
    'ablation_summary': ablation_df,
    'bootstrap_ci': ci_df,
    'model_comparison': model_comparison_df,
    'pipeline_evaluation': pipeline_summary_df,
    'stage3_regression_summary': stage3_summary_df,
    'test_predictions': test_pipeline,
    'val_predictions': val_pipeline,
}

for name, df in parquet_exports.items():
    path = EVAL_DIR / f'{name}.parquet'
    con.register(f'export_{name}', df)
    con.execute(f"COPY export_{name} TO '{path.as_posix()}' (FORMAT PARQUET, COMPRESSION 'zstd')")
    con.unregister(f'export_{name}')

print(f'Saved stage 2 ranker to: {stage2_model_path}')
print(f'Saved stage 1 classifier to: {stage1_model_path}')
print(f'Saved stage 1 calibrator to: {stage1_calibrator_path}')
print(f'Saved stage 3 regressor to: {stage3_model_path}')
print(f'Saved LR ranking baseline to: {lr_model_path}')
print(f'Saved LR timing baseline to: {lr_time_model_path}')
print(f'Saved training summary to: {training_summary_path}')
print(f'Saved pipeline summary to: {pipeline_summary_path}')
print(f'Saved {len(parquet_exports)} evaluation parquets to: {EVAL_DIR}')
print()
print('Done.')

## 10. Conclusion

### Key Findings

1. **Non-linear models substantially outperform linear baselines across both tasks.** For ranking, the progression from naive popularity (recall@5 = 0.071) to Logistic Regression (0.581) to XGBRanker (0.669) demonstrates two things: (a) the features carry strong predictive signal — LR achieves 8.2× the recall of the naive baseline, and (b) non-linear feature interactions add another 15.2% relative improvement. For timing, the same pattern holds: Linear Regression establishes a baseline MAE, and the XGBRegressor improves upon it (test MAE = 7.76 days) by capturing non-linear dynamics.

2. **The XGBRanker is the right formulation for country prediction.** By directly optimizing ndcg with listwise gradients, the model produces well-ordered country lists rather than independent per-country probabilities. This aligns with Spotify's business need to prioritize markets: ndcg@5 = 0.727, a 22.4% improvement over logistic regression's 0.594, confirming that the ranker places relevant countries *higher* in the list.

3. **Temporal cross-validation is essential.** Music diffusion patterns change over time — our expanding-window temporal CV (3 folds over 5 time blocks) ensures the model generalizes to future periods. Training on 2017–2019 and testing on 2021 avoids temporal leakage that standard k-fold CV would introduce.

4. **The Stage 1 gate hurts more than it helps.** The pre-filtering classifier, despite excellent calibration (Brier score improved from 0.854 to 0.067 with isotonic calibration), consistently drops recall by 21–43% depending on threshold (pfloor=0.20: recall drops to 0.459; pfloor=0.25: drops to 0.385). For a system where missing a spreading track means missing a market opportunity, the standalone ranker at recall@5 = 0.669 is the clear winner.

5. **Cultural and geographic features dominate both ranking models.** Both agree on the key drivers:
   - *Logistic regression coefficients* reveal *direction*: `artist_prior_unique_regions` (+0.852) and `same_language_flag` (+0.733) are the strongest positive predictors; `cultural_dist_min` (−0.174) confirms cultural distance *decreases* spread probability.
   - *XGBRanker gain importance* reveals *magnitude*: origin-target relationship features (total gain = 239.5) dominate, followed by current chart footprint (146.1), target country priors (33.2), and artist history (25.9).
   - Both confirm music spreads along cultural corridors (Latin America, Scandinavia, English-speaking markets), aligning with Hofstede's (2001) cultural dimensions theory and Straubhaar's (1991) cultural proximity framework.

6. **Bayesian hyperparameter optimization provides marginal gains over random search.** The final model matches our random-search baseline (NB 09) on recall@5 (0.669) with slight ndcg improvement (0.725 → 0.727). Optuna's TPE sampler pruned 23 of 50 trials early, saving ~46% of compute, but the similar end result suggests **feature engineering, not hyperparameter tuning, is the binding constraint**.

### Model Performance Ladder

| Model | Task | Metric | Value | Complexity |
|-------|------|--------|-------|------------|
| Naive popularity baseline | Ranking | recall@5 | 0.071 | None (heuristic) |
| Logistic Regression | Ranking | recall@5 | 0.581 | Linear, interpretable |
| **XGBRanker** | **Ranking** | **recall@5** | **0.669** | Non-linear, Optuna-tuned |
| Linear Regression | Timing | MAE | *see results* | Linear, interpretable |
| **XGBRegressor** | **Timing** | **MAE** | **7.76 days** | Non-linear, Optuna-tuned |

Each step up the complexity ladder delivers a meaningful improvement. The 95% bootstrap confidence intervals — recall@5 ∈ [0.652, 0.687], ndcg@5 ∈ [0.712, 0.742] — confirm the ranking results are statistically robust.

### Business Impact

For Spotify's operations, this model enables:
- **Proactive market targeting:** The model correctly predicts 2 out of 3 future chart countries (recall@5 = 0.669), and 87.4% of tracks have at least one correct country in the top-5 (hit_rate@5 = 0.874).
- **Resource allocation:** The top-5 predictions tell marketing teams where to focus limited budgets. LR coefficients provide transparent justification — "we're targeting Brazil because the artist has charted there before (+0.609) and it shares a language with the origin country (+0.733)."
- **Timing optimization:** The days-to-entry regressor adds a temporal dimension — with 48.4% of predictions within 3 days and 69.3% within 7 days, teams can sequence campaign rollouts (MAE = 7.76 days).
- **Full interpretability:** The combination of LR coefficients (feature direction for both tasks) and XGB gain importance (feature magnitude) provides stakeholders with a complete picture of *why* predictions are made.

### Limitations

- **Feature saturation:** The marginal improvement from Optuna over random search (ndcg@5: 0.725 → 0.727) indicates diminishing returns from the current feature set. Additional signal sources (e.g., audio embeddings, social media mentions, playlist editorial data) may be needed for further gains.
- **Cold-start problem:** The model requires a track's first chart appearance as the observation point — it cannot predict spread for tracks that haven't charted anywhere yet.
- **Temporal generalization:** The 2021 test set captures post-COVID streaming patterns, but the music industry continues to evolve. Periodic retraining on recent data would be necessary in production.
- **Geographic bias:** 19.4% of country pairs lack Hofstede cultural distance data, concentrated among non-Western countries. The model may underperform for markets not well-represented in Hofstede's framework.
- **Regressor precision:** While 48.4% of timing predictions fall within 3 days, the overall MAE of 7.76 days means roughly half of predictions are off by more than a week — sufficient for campaign planning but not for precise scheduling.

### Future Work

- **Richer features:** Incorporate Spotify audio features (danceability, energy, valence), social media signals (TikTok mentions, YouTube views), and playlist-level features (editorial vs algorithmic placement).
- **Deep learning exploration:** Sequence models (e.g., Transformer over a track's chart trajectory) could capture temporal diffusion dynamics that static features miss.
- **Multi-objective optimization:** Jointly optimize recall and diversity to ensure recommendations span different cultural regions rather than concentrating on a few dominant markets.
- **Online learning:** Implement incremental model updates as new chart data arrives, reducing the lag between training and deployment.